"use client";

import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { CalendarDays, Check, ChevronLeft, ChevronRight, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { addDays, addMonths, indiaDateKey, periodDates } from "@/lib/dates";
import { cn } from "@/lib/utils";

type PlanTracker={id:number;name:string;detail:string};
type Cadence="daily"|"weekdays"|"weekends"|"weekly";
const parsed=(key:string)=>new Date(`${key}T12:00:00Z`);
const format=(key:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat("en-IN",{...options,timeZone:"Asia/Kolkata"}).format(parsed(key));

export function PlanAhead({range,trackers,onClose}:{range:"week"|"month";trackers:PlanTracker[];onClose:()=>void}){
 const initialAnchor=range==="week"?addDays(indiaDateKey(),7):addMonths(indiaDateKey(),1),[anchor,setAnchor]=useState(initialAnchor),[selected,setSelected]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");const dates=useMemo(()=>periodDates(range,anchor),[range,anchor]);
 useEffect(()=>{let active=true;setLoading(true);setSaved(false);fetch(`/api/plan?range=${range}&anchor=${anchor}`,{cache:"no-store"}).then(response=>response.ok?response.json():Promise.reject()).then(data=>{if(active)setSelected(new Set((data.items as {trackerId:number;date:string}[]).map(item=>`${item.trackerId}:${item.date}`)))}).catch(()=>active&&setError("We couldn't load this plan.")).finally(()=>active&&setLoading(false));return()=>{active=false}},[range,anchor]);
 const included=(trackerId:number)=>dates.some(date=>selected.has(`${trackerId}:${date}`));
 const applyDates=(trackerId:number,nextDates:string[])=>setSelected(current=>{const next=new Set([...current].filter(key=>!key.startsWith(`${trackerId}:`)));nextDates.forEach(date=>next.add(`${trackerId}:${date}`));return next});
 const toggleDate=(trackerId:number,date:string)=>setSelected(current=>{const next=new Set(current),key=`${trackerId}:${date}`;if(next.has(key))next.delete(key);else next.add(key);return next});
 const cadence=(trackerId:number,value:Cadence)=>{const chosen=value==="daily"?dates:value==="weekdays"?dates.filter(date=>{const day=parsed(date).getUTCDay();return day>0&&day<6}):value==="weekends"?dates.filter(date=>[0,6].includes(parsed(date).getUTCDay())):dates.filter((_,index)=>index%7===0);applyDates(trackerId,chosen)};
 const shift=(direction:number)=>setAnchor(current=>range==="week"?addDays(current,direction*7):addMonths(current,direction));
 async function save(){setSaving(true);setError("");const items=[...selected].map(key=>{const [trackerId,date]=key.split(":");return {trackerId:Number(trackerId),date}});const response=await fetch("/api/plan",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({range,anchor,items})});setSaving(false);if(response.ok){setSaved(true);window.dispatchEvent(new Event("plan:updated"))}else setError("Your plan could not be saved.")}
 const periodLabel=range==="week"?`${format(dates[0],{month:"short",day:"numeric"})} – ${format(dates.at(-1)!,{month:"short",day:"numeric",year:"numeric"})}`:format(dates[0],{month:"long",year:"numeric"});
 return <div className="fixed inset-0 z-[9998] flex items-end justify-center bg-black/70 backdrop-blur-sm sm:items-center sm:p-5" onMouseDown={event=>{if(event.target===event.currentTarget)onClose()}}><motion.section initial={{opacity:0,y:24,scale:.99}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:18}} role="dialog" aria-modal="true" aria-labelledby="plan-title" className="max-h-[94vh] w-full max-w-4xl overflow-y-auto rounded-t-[2rem] border border-white/10 bg-[#15131c] p-5 text-white shadow-2xl sm:rounded-[2rem] sm:p-7">
  <div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-lavender">Plan ahead · 2 simple steps</p><h2 id="plan-title" className="mt-2 text-2xl font-semibold">Shape your {range}.</h2><p className="mt-2 max-w-xl text-xs leading-5 text-white/45">Choose the period, then include only what matters. Use a rhythm preset or fine-tune individual days.</p></div><button onClick={onClose} aria-label="Close planner" className="focus-ring grid size-11 shrink-0 place-items-center rounded-xl bg-white/5"><X size={16}/></button></div>
  <section className="mt-7 rounded-2xl border border-white/[.08] bg-white/[.035] p-4"><div className="flex items-center justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">Step 1 · Choose {range}</p><p className="mt-1 text-sm font-semibold">{periodLabel}</p></div><div className="flex gap-2"><button onClick={()=>shift(-1)} aria-label={`Previous ${range}`} className="focus-ring grid size-11 place-items-center rounded-xl border border-white/10 hover:bg-white/5"><ChevronLeft size={15}/></button><button onClick={()=>shift(1)} aria-label={`Next ${range}`} className="focus-ring grid size-11 place-items-center rounded-xl border border-white/10 hover:bg-white/5"><ChevronRight size={15}/></button></div></div></section>
  <section className="mt-4"><div className="mb-3 flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">Step 2 · Add your rhythm</p><p className="mt-1 text-xs text-white/45">{selected.size} planned check-ins</p></div>{saved&&<span role="status" className="flex items-center gap-1 text-xs font-semibold text-[#b9ead1]"><Check size={13}/>Saved</span>}</div>{loading?<div className="h-48 animate-pulse rounded-2xl bg-white/[.04]"/>:<div className="space-y-2">{trackers.map(tracker=><article key={tracker.id} className={cn("rounded-2xl border p-4 transition",included(tracker.id)?"border-lavender/30 bg-lavender/[.07]":"border-white/[.07] bg-white/[.025]")}><div className="flex items-center gap-3"><button role="switch" aria-checked={included(tracker.id)} onClick={()=>included(tracker.id)?applyDates(tracker.id,[]):cadence(tracker.id,range==="month"?"weekdays":"daily")} className={cn("focus-ring relative h-7 w-12 shrink-0 rounded-full transition",included(tracker.id)?"bg-lavender":"bg-white/15")}><span className={cn("absolute top-1 size-5 rounded-full bg-white transition-transform",included(tracker.id)?"translate-x-1":"-translate-x-5")}/></button><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold">{tracker.name}</h3><p className="mt-1 truncate text-[10px] text-white/35">{tracker.detail}</p></div><span className="text-[10px] text-white/35">{dates.filter(date=>selected.has(`${tracker.id}:${date}`)).length} days</span></div>{included(tracker.id)&&<div className="mt-4 border-t border-white/[.07] pt-4"><div className="flex flex-wrap gap-2">{(["daily","weekdays","weekends","weekly"] as Cadence[]).map(value=><button key={value} onClick={()=>cadence(tracker.id,value)} className="focus-ring min-h-9 rounded-lg border border-white/[.08] px-3 text-[9px] font-semibold capitalize text-white/55 hover:bg-white/5 hover:text-white">{value}</button>)}</div>{range==="week"&&<div className="mt-3 grid grid-cols-7 gap-1.5">{dates.map(date=>{const active=selected.has(`${tracker.id}:${date}`);return <button key={date} onClick={()=>toggleDate(tracker.id,date)} aria-pressed={active} className={cn("focus-ring min-h-12 rounded-xl border text-center",active?"border-lavender/40 bg-lavender text-black":"border-white/[.08] text-white/40")}><span className="block text-[8px] uppercase">{format(date,{weekday:"narrow"})}</span><strong className="text-[10px]">{parsed(date).getUTCDate()}</strong></button>})}</div>}</div>}</article>)}</div>}</section>
  {error&&<p role="alert" className="mt-4 text-xs text-negative">{error}</p>}<div className="sticky bottom-0 -mx-5 mt-6 flex items-center justify-between gap-3 border-t border-white/[.07] bg-[#15131c]/95 px-5 pt-4 backdrop-blur-xl sm:-mx-7 sm:px-7"><span className="hidden text-[10px] text-white/35 sm:block"><CalendarDays className="mr-2 inline" size={13}/>{periodLabel}</span><div className="ml-auto flex gap-3"><Button onClick={onClose} variant="ghost" className="border border-white/10 text-white">Cancel</Button><Button onClick={save} disabled={saving||loading} className="bg-white text-black">{saving?"Saving…":`Save ${range} plan`}</Button></div></div>
 </motion.section></div>
}
