"use client";

import { useEffect, useId, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { Check, ChevronDown, CircleDashed, Coffee, Minus, RotateCcw, X } from "lucide-react";
import { cn } from "@/lib/utils";

export type TrackerStatus="complete"|"partial"|"missed"|"skip"|"rest"|"none";
const options:[TrackerStatus,string,typeof Check,string,string][]=[
 ['complete','Complete',Check,'text-[#b9ead1]','Done for today'],['partial','Partial',Minus,'text-[#e8d29a]','Some progress made'],['missed','Missed',X,'text-[#e6aab5]','Not completed'],['skip','Planned skip',CircleDashed,'text-[#c2b9d7]','Intentionally skipped'],['rest','Rest day',Coffee,'text-[#aeb8e8]','Recovery is the plan'],
];
export function StatusControl({status,onChange,label}:{status:TrackerStatus;onChange:(status:TrackerStatus)=>void;label:string}){
 const [open,setOpen]=useState(false); const [mounted,setMounted]=useState(false); const [pos,setPos]=useState({top:0,right:0});
 const trigger=useRef<HTMLButtonElement>(null); const menu=useRef<HTMLDivElement>(null); const menuId=useId(); const active=options.find(x=>x[0]===status); const Icon=active?.[2]??Check;
 useEffect(()=>setMounted(true),[]);
 useEffect(()=>{if(!open)return;const place=()=>{const r=trigger.current?.getBoundingClientRect();if(r)setPos({top:r.bottom+8,right:Math.max(12,window.innerWidth-r.right)})};place();const close=(event:PointerEvent)=>{const node=event.target as Node;if(!trigger.current?.parentElement?.contains(node)&&!menu.current?.contains(node))setOpen(false)};window.addEventListener('pointerdown',close);window.addEventListener('resize',place);window.addEventListener('scroll',place,true);return()=>{window.removeEventListener('pointerdown',close);window.removeEventListener('resize',place);window.removeEventListener('scroll',place,true)}},[open]);
 const choose=(value:TrackerStatus)=>{onChange(value);setOpen(false)};
 return <div className="relative flex shrink-0"><button onClick={()=>onChange(status==='complete'?'none':'complete')} aria-label={`${status==='complete'?'Unmark':'Complete'} ${label}`} className={cn("focus-ring relative grid size-11 place-items-center rounded-l-xl border transition-all duration-200 active:scale-90",status==='complete'?"border-[#b9ead1]/40 bg-[#b9ead1]/15 text-[#c9f4dc] shadow-[0_0_24px_rgba(185,234,209,.14)]":status!=='none'?"border-white/10 bg-white/[.08] "+active?.[3]:"border-white/10 bg-white/[.045] text-white/30 hover:border-lavender/40 hover:text-white")}><Icon size={17}/>{status==='complete'&&<span className="pointer-events-none absolute inset-0 animate-ping rounded-xl border border-[#b9ead1]/20 [animation-iteration-count:1]"/>}</button><button ref={trigger} onClick={()=>setOpen(x=>!x)} aria-label={`More statuses for ${label}`} aria-expanded={open} aria-controls={menuId} className="focus-ring grid w-7 place-items-center rounded-r-xl border border-l-0 border-white/10 bg-white/[.04] text-white/35 hover:bg-white/[.1] hover:text-white"><ChevronDown size={12}/></button>{mounted&&open&&createPortal(<div ref={menu} id={menuId} role="menu" style={{position:'fixed',top:pos.top,right:pos.right}} className="z-[9999] w-52 origin-top-right animate-[status-in_.16s_ease-out] rounded-2xl border border-white/12 bg-[#1b1923]/98 p-1.5 shadow-[0_24px_70px_rgba(0,0,0,.7)] backdrop-blur-2xl">{options.map(([value,text,ChoiceIcon,color,hint])=><button role="menuitemradio" aria-checked={status===value} key={value} onClick={()=>choose(value)} className={cn("focus-ring flex min-h-12 w-full items-center gap-3 rounded-xl px-3 text-left hover:bg-white/[.07]",color)}><span className="grid size-7 place-items-center rounded-lg bg-white/[.05]"><ChoiceIcon size={14}/></span><span><strong className="block text-[11px]">{text}</strong><small className="mt-0.5 block text-[8px] font-medium text-white/30">{hint}</small></span>{status===value&&<Check size={12} className="ml-auto"/>}</button>)}{status!=='none'&&<button onClick={()=>choose('none')} className="focus-ring flex min-h-10 w-full items-center gap-2.5 rounded-xl px-3 text-[10px] text-white/40 hover:bg-white/[.06]"><RotateCcw size={12}/>Clear status</button>}</div>,document.body)}</div>;
}
