"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import { Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { Activity,ArrowDownRight,ArrowUpRight,Clock3,Flame,RefreshCw,Target,TrendingUp } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ScoreRing } from "@/components/charts/analytics-charts";
import type { AnalyticsPoint,AnalyticsSnapshot } from "@/lib/analytics";
import { cn } from "@/lib/utils";

const glass="border border-line bg-surface shadow-soft backdrop-blur-xl";
const periods=[{label:"7 days",days:7},{label:"30 days",days:30},{label:"3 months",days:90},{label:"Year",days:365}] as const;
const empty:AnalyticsSnapshot={generatedAt:new Date(0).toISOString(),rangeDays:30,score:0,change:0,consistency:0,currentStreak:0,bestStreak:0,completed:0,adherence:0,restDays:0,trend:[],weekdays:[],heatmap:[],habits:[]};

export function AnalyticsScreen(){
 const [days,setDays]=useState<7|30|90|365>(30),[data,setData]=useState(empty),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
 const load=useCallback(async(silent=false)=>{if(!silent)setLoading(true);else setRefreshing(true);try{const response=await fetch(`/api/analytics?days=${days}`,{cache:"no-store"});if(!response.ok)throw new Error();setData(await response.json());setError("")}catch{setError("Your live dashboard could not be refreshed.")}finally{setLoading(false);setRefreshing(false)}},[days]);
 useEffect(()=>{load();const timer=window.setInterval(()=>{if(document.visibilityState==="visible")load(true)},60000);const onVisible=()=>{if(document.visibilityState==="visible")load(true)};const onTracker=()=>load(true);document.addEventListener("visibilitychange",onVisible);window.addEventListener("tracker:updated",onTracker);return()=>{window.clearInterval(timer);document.removeEventListener("visibilitychange",onVisible);window.removeEventListener("tracker:updated",onTracker)}},[load]);
 const sampled=useMemo(()=>sample(data.trend,days===365?24:days===90?18:days===30?15:7),[data.trend,days]);const best=[...data.weekdays].sort((a,b)=>b.completion-a.completion)[0],weak=[...data.weekdays].sort((a,b)=>a.completion-b.completion)[0];
 return <AppShell><main className="mx-auto min-h-screen w-full min-w-0 max-w-[1480px] overflow-x-clip px-4 pb-28 pt-6 sm:px-7 lg:px-10 lg:pb-14 lg:pt-9">
  <header className="mb-8 flex min-w-0 flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0"><div className="mb-3 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-lavender/70"><span className="size-1.5 rounded-full bg-positive shadow-[0_0_10px_#77b69a]"/>Live from your check-ins</div><h1 className="text-[clamp(2.2rem,5vw,4.2rem)] font-semibold leading-none tracking-[-.065em]">Your progress, in perspective.</h1><p className="mt-4 max-w-xl text-sm leading-relaxed text-white/45">No demo numbers. Every chart refreshes from your saved tracker history.</p></div><div className="flex min-w-0 max-w-full items-center gap-2"><div className="flex min-w-0 flex-1 gap-1 overflow-x-auto rounded-2xl border border-line bg-surface p-1 shadow-sm [scrollbar-width:none]" role="tablist" aria-label="Dashboard timeframe">{periods.map(item=><button key={item.days} role="tab" aria-selected={days===item.days} onClick={()=>setDays(item.days)} className={cn("focus-ring min-h-11 shrink-0 whitespace-nowrap rounded-xl px-4 text-[10px] font-bold",days===item.days?"border border-line bg-surface-raised text-ink shadow-sm":"text-muted hover:text-ink")}>{item.label}</button>)}</div><button onClick={()=>load(true)} aria-label="Refresh live analytics" className="focus-ring grid size-11 shrink-0 place-items-center rounded-xl border border-white/10 bg-white/[.04] text-white/50"><RefreshCw size={15} className={refreshing?"animate-spin":""}/></button></div></header>
  {error&&<p role="status" className="mb-4 rounded-xl border border-negative/20 bg-negative/10 px-4 py-3 text-xs text-negative">{error}</p>}
  <section className="mb-7 grid min-w-0 grid-cols-2 gap-3 md:grid-cols-5"><Metric label="Completion" value={`${data.score}%`} meta={signed(data.change,"vs prior")}/><Metric label="Consistency" value={`${data.consistency}%`} meta="days with check-ins"/><Metric label="Current streak" value={`${data.currentStreak}d`} meta={`best ${data.bestStreak}d`}/><Metric label="Completed" value={String(data.completed)} meta="saved check-ins"/><Metric className="col-span-2 md:col-span-1" label="Plan adherence" value={`${data.adherence}%`} meta="planned days completed"/></section>
  <section className="grid gap-5 xl:grid-cols-[1.55fr_.75fr]"><article className={cn(glass,"min-w-0 rounded-[1.8rem] p-4 sm:p-7")}><div className="mb-6 flex items-end justify-between"><div><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">Completion trend</p><h2 className="mt-2 text-lg font-semibold sm:text-xl">Momentum from saved entries.</h2></div><span className={cn("flex items-center gap-1 text-[10px]",data.change>=0?"text-positive":"text-negative")}>{data.change>=0?<ArrowUpRight size={13}/>:<ArrowDownRight size={13}/>} {Math.abs(data.change)}%</span></div>{loading?<Skeleton className="h-[290px]"/>:<Trend points={sampled}/>}</article><article className={cn(glass,"relative flex min-h-[330px] flex-col items-center justify-center overflow-hidden rounded-[1.8rem] p-6 text-center")}><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(115,86,232,.18),transparent_64%)]"/><div className="relative"><ScoreRing score={data.score} label="Overall progress" size={205}/></div><p className="relative mt-3 max-w-[240px] text-[11px] leading-relaxed text-white/40">{data.score?`${data.completed} completed check-ins in this range.`:"Your dashboard starts at zero and grows with every real check-in."}</p></article></section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[.85fr_1.15fr]"><article className={cn(glass,"rounded-[1.8rem] p-5 sm:p-7")}><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">Daily performance</p><h2 className="mt-2 text-xl font-semibold">Where your rhythm bends.</h2><Bars points={data.weekdays}/><div className="mt-5 grid grid-cols-2 gap-3 border-t border-white/[.06] pt-5"><Small label="Best day" value={`${best?.day||"—"} · ${best?.completion||0}%`}/><Small label="Needs attention" value={`${weak?.day||"—"} · ${weak?.completion||0}%`}/></div></article><article className={cn(glass,"rounded-[1.8rem] p-5 sm:p-7")}><div className="flex justify-between"><div><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">Activity</p><h2 className="mt-2 text-xl font-semibold">A year of showing up.</h2></div><Activity size={17} className="text-lavender"/></div><Heatmap cells={data.heatmap}/><div className="mt-7 grid grid-cols-3 gap-2 sm:gap-3"><Small label="Consistency" value={`${data.consistency}%`}/><Small label="Streak" value={`${data.currentStreak} days`}/><Small label="Rest days" value={String(data.restDays)}/></div></article></section>
  <section className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><HabitPerformance habits={data.habits}/><Signals data={data}/></section>
  <div className="mt-5 flex items-center justify-end gap-2 text-[9px] text-white/25"><Clock3 size={11}/>Updated {new Date(data.generatedAt).toLocaleTimeString("en-IN",{hour:"numeric",minute:"2-digit"})} · auto-refreshes every minute while this tab is active</div>
 </main></AppShell>}

function sample(points:AnalyticsPoint[],maximum:number){if(points.length<=maximum)return points;const step=Math.ceil(points.length/maximum);return points.filter((_,index)=>index%step===0||index===points.length-1)}
function signed(value:number,suffix:string){return `${value>=0?"+":""}${value}% ${suffix}`}
function TrendTooltip({active,payload}:{active?:boolean;payload?:Array<{payload:AnalyticsPoint}>}){const point=payload?.[0]?.payload;if(!active||!point)return null;return <div className="min-w-40 rounded-2xl border border-white/12 bg-surface-raised/95 p-3.5 text-white shadow-2xl"><p className="mb-2 text-xs font-semibold">{point.label}</p><p className="text-xs text-white/55">Completion <strong className="float-right text-white">{point.completion}%</strong></p><p className="mt-1 text-xs text-white/55">Complete <strong className="float-right text-white">{point.completed}/{point.planned}</strong></p></div>}
function Trend({points}:{points:AnalyticsPoint[]}){return <div className="h-[260px] w-full sm:h-[320px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={points} margin={{top:10,right:6,bottom:0,left:-18}}><defs><linearGradient id="liveArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9c7cff" stopOpacity={.32}/><stop offset="1" stopColor="#9c7cff" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--line)" strokeDasharray="3 6"/><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{fill:"var(--subtle)",fontSize:9}} minTickGap={16}/><YAxis domain={[0,100]} ticks={[0,50,100]} axisLine={false} tickLine={false} tickFormatter={value=>`${value}%`} tick={{fill:"var(--subtle)",fontSize:9}}/><Tooltip content={<TrendTooltip/>}/><Area type="monotone" dataKey="completion" stroke="#a888f5" strokeWidth={3} fill="url(#liveArea)" dot={false} activeDot={{r:5,fill:"var(--surface-raised)",stroke:"#8877db",strokeWidth:3}}/></AreaChart></ResponsiveContainer></div>}
function Bars({points}:{points:Array<{day:string;completion:number}>}){return <div className="mt-8 flex h-48 items-end gap-2">{points.map(point=><div key={point.day} className="flex h-full flex-1 flex-col justify-end gap-2 text-center"><span className="text-[9px] text-white/30">{point.completion}%</span><div className="min-h-1 w-full rounded-t-lg bg-gradient-to-t from-violet/45 to-lavender" style={{height:`${Math.max(2,point.completion)}%`}}/><span className="text-[9px] font-semibold text-white/35">{point.day.slice(0,1)}</span></div>)}</div>}
function Heatmap({cells}:{cells:Array<{date:string;value:number}>}){return <div className="mt-8 grid min-w-0 grid-flow-col grid-rows-7 gap-[2px] overflow-hidden sm:gap-[3px]" style={{gridTemplateColumns:"repeat(53,minmax(0,1fr))"}}>{cells.map(cell=><span key={cell.date} title={`${cell.date} · ${cell.value}%`} className={cn("aspect-square min-w-0 rounded-[2px]",cell.value===0&&"bg-white/5",cell.value>0&&cell.value<35&&"bg-lilac/35",cell.value>=35&&cell.value<70&&"bg-lavender/65",cell.value>=70&&"bg-violet")}/>)}</div>}
function Metric({label,value,meta,className}:{label:string;value:string;meta:string;className?:string}){return <article className={cn("min-h-28 min-w-0 rounded-2xl border border-line bg-surface p-4 shadow-soft",className)}><p className="truncate text-[9px] font-bold uppercase tracking-widest text-white/40">{label}</p><p className="mt-3 text-2xl font-semibold tracking-[-.045em]">{value}</p><p className="mt-2 truncate text-[9px] text-white/32">{meta}</p></article>}
function Small({label,value}:{label:string;value:string}){return <div className="min-w-0 rounded-xl bg-white/[.04] p-3"><p className="truncate text-[9px] text-white/40">{label}</p><strong className="mt-1 block truncate text-xs sm:text-sm">{value}</strong></div>}
function HabitPerformance({habits}:{habits:AnalyticsSnapshot["habits"]}){return <article className={cn(glass,"rounded-[1.8rem] p-5 sm:p-7")}><div className="flex justify-between"><div><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">Habit performance</p><h2 className="mt-2 text-xl font-semibold">Strong and soft signals.</h2></div><Target size={18} className="text-lavender"/></div><div className="mt-8 space-y-5">{habits.slice(0,7).map(habit=><div key={habit.id} className="grid grid-cols-[95px_1fr_38px] items-center gap-3 sm:grid-cols-[140px_1fr_42px]"><span className="truncate text-[11px] text-white/55">{habit.name}</span><div className="h-1.5 rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-violet transition-all duration-700" style={{width:`${habit.completion}%`}}/></div><strong className="text-[10px] text-lavender">{habit.completion}%</strong></div>)}{!habits.length&&<p className="py-12 text-center text-xs text-white/30">Create a tracker to begin your analytics.</p>}</div></article>}
function Signals({data}:{data:AnalyticsSnapshot}){const strongest=data.habits[0];return <article className={cn(glass,"rounded-[1.8rem] p-5 sm:p-7")}><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">What the data says</p><h2 className="mt-2 text-xl font-semibold">Useful signals, without guesses.</h2><div className="mt-6 space-y-3"><Signal icon={TrendingUp} label="Momentum" copy={data.change===0?"More history is needed to establish a trend.":`Completion is ${Math.abs(data.change)}% ${data.change>0?"higher":"lower"} than the prior range.`}/><Signal icon={Flame} label="Strongest tracker" copy={strongest?`${strongest.name} leads at ${strongest.completion}% completion.`:"No completed trackers yet."}/><Signal icon={Target} label="Planning" copy={data.adherence?`${data.adherence}% of scheduled tracker-days were completed.`:"Plan a week or month to measure adherence."}/></div></article>}
function Signal({icon:Icon,label,copy}:{icon:typeof Target;label:string;copy:string}){return <div className="flex gap-3 rounded-2xl bg-white/[.035] p-4"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-lavender/10 text-lavender"><Icon size={15}/></span><div><p className="text-[9px] font-bold uppercase tracking-widest text-white/35">{label}</p><p className="mt-1 text-xs leading-5 text-white/65">{copy}</p></div></div>}
function Skeleton({className}:{className:string}){return <div className={cn("animate-pulse rounded-2xl bg-white/[.035]",className)}/>}
