"use client";

import Link from "next/link";
import { ArrowLeft, CalendarDays, Check, Dumbbell, Flame, Footprints, Moon, Plus, Sparkles, Target } from "lucide-react";
import { ScoreRing } from "@/components/charts/analytics-charts";
import { Button } from "@/components/ui/button";

const habits=[['Run 4x/week','3 of 4',75,Footprints],['Strength 2x/week','2 of 2',100,Dumbbell],['Sleep 7.5h','5 of 7',71,Moon],['Stretch 10m','6 of 7',86,Flame]] as const;
export function GoalsScreen(){return <div className="min-h-screen bg-canvas"><header className="border-b border-line"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 text-sm font-bold"><span className="grid size-8 place-items-center rounded-xl bg-ink text-canvas"><Sparkles size={14}/></span>form</Link><Button size="sm"><Plus size={14}/>New goal</Button></div></header><main className="mx-auto max-w-6xl px-5 py-10 sm:px-8"><Link href="/today" className="mb-8 inline-flex items-center gap-1 text-xs text-muted"><ArrowLeft size={13}/>Back to today</Link><div className="mb-12 max-w-3xl"><p className="eyebrow mb-3 text-violet">Goal system</p><h1 className="display-md">Run a Half Marathon</h1><p className="body-lg mt-4 text-muted">Race day · 18 October · 8 weeks remaining</p></div><div className="grid gap-8 lg:grid-cols-[1.25fr_.75fr]"><section><div className="mb-6 flex items-end justify-between"><div><h2 className="heading-md">Everyday actions, one direction.</h2><p className="mt-2 text-sm text-muted">Four habits connected to this goal</p></div><Target className="text-violet"/></div><div className="relative space-y-3 before:absolute before:bottom-8 before:left-[27px] before:top-8 before:w-px before:bg-line">{habits.map(([name,value,progress,Icon],i)=><div key={name} className="relative flex items-center gap-4 rounded-2xl border border-line bg-surface p-4 backdrop-blur"><div className="z-10 grid size-14 place-items-center rounded-2xl bg-surface-raised shadow-sm"><Icon size={19} className="text-violet"/></div><div className="flex-1"><div className="flex justify-between"><strong className="text-sm">{name}</strong><span className="text-xs text-muted">{value}</span></div><div className="mt-3 h-1.5 rounded-full bg-line"><div className="h-full rounded-full bg-violet" style={{width:`${progress}%`}}/></div></div>{i<2&&<Check size={15} className="text-violet"/>}</div>)}</div></section><aside className="rounded-[2rem] bg-ink p-7 text-canvas"><div className="flex justify-center"><ScoreRing score={76} label="Goal health" size={210}/></div><div className="mt-7 space-y-6">{[['Milestones',60],['Habit adherence',82],['Training volume',74]].map(([name,value])=><div key={name as string}><div className="mb-2 flex justify-between text-xs"><span className="opacity-55">{name as string}</span><strong>{value}%</strong></div><div className="h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-lavender" style={{width:`${value}%`}}/></div></div>)}</div><div className="mt-8 flex items-center gap-3 border-t border-white/10 pt-6"><CalendarDays size={17} className="text-lavender"/><div><p className="text-xs font-bold">Next milestone</p><p className="text-[10px] opacity-50">Complete a 15 km long run</p></div></div></aside></div></main></div>}
