"use client";

import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUp, BrainCircuit, Dumbbell, Flame, Moon, Smartphone, Sparkles, Target, TrendingUp } from "lucide-react";
import { ActivityHeatmap, LifeRadar, ScoreRing, WeeklyLineChart } from "@/components/charts/analytics-charts";
import { Button } from "@/components/ui/button";

const areaScores=[['Health',83],['Career',74],['Learning',91],['Discipline',78],['Wellness',69],['Finance',86]];
export function IntelligenceSections(){return <>
 <section className="relative left-1/2 w-screen -translate-x-1/2 bg-[linear-gradient(to_bottom,#f8f7fb_0%,#d9ccff_18%,#342366_48%,#0c0c10_75%)] py-32 text-white dark:bg-[linear-gradient(to_bottom,#0c0c10,#241846,#0c0c10)] md:py-44"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow mb-5 text-violet md:text-lilac">From action to understanding</p><h2 className="display-md text-ink md:text-white">Then turn consistency into insight.</h2><p className="body-lg mt-6 text-ink/60 md:text-white/50">See the patterns underneath the progress—without becoming a data analyst.</p></div><div className="mt-20 rounded-[2rem] border border-white/10 bg-[#0c0c10]/90 p-5 shadow-[0_50px_140px_rgba(0,0,0,.45)] backdrop-blur-xl sm:p-8"><div className="mb-9 flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-white/35">Weekly perspective</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Your habits are gaining shape.</h3></div><Link href="/analytics"><Button className="bg-white text-black" size="sm">Open analytics <ArrowRight size={13}/></Button></Link></div><div className="grid gap-8 lg:grid-cols-[1.6fr_.6fr]"><div className="h-72"><WeeklyLineChart dark/></div><div className="flex items-center justify-center"><ScoreRing score={82} size={200}/></div></div></div></div></section>
 <section className="py-24 md:py-36"><div className="grid items-center gap-16 lg:grid-cols-2"><div><p className="eyebrow mb-4 text-violet">Life Score</p><h2 className="display-md">See the whole picture.</h2><p className="body-lg mt-6 text-muted">One calm signal composed from the areas and metrics you choose. It is a reflection aid—not a judgment of personal worth.</p><div className="mt-8 grid grid-cols-2 gap-x-8 gap-y-5">{areaScores.map(([name,value])=><div key={name as string}><div className="mb-2 flex justify-between text-xs"><span className="text-muted">{name}</span><strong>{value}</strong></div><div className="h-1.5 rounded-full bg-line"><div className="h-full rounded-full bg-violet" style={{width:`${value}%`}}/></div></div>)}</div></div><div className="relative flex min-h-[430px] items-center justify-center rounded-full bg-[radial-gradient(circle,rgba(217,204,255,.55),transparent_64%)] dark:bg-[radial-gradient(circle,rgba(115,86,232,.2),transparent_65%)]"><div className="absolute size-80 rounded-full border border-line"/><div className="absolute size-64 rounded-full border border-line"/><ScoreRing score={81} label="Life Score" size={270}/></div></div></section>
 <section className="border-y border-line py-24 md:py-36"><div className="grid items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow mb-4 text-violet">Life balance</p><h2 className="display-md">Balance what matters.</h2><p className="body-lg mt-6 text-muted">Not perfect symmetry. A legible picture of what has your energy—and what may need a little more room.</p></div><div className="h-[430px] rounded-[2rem] bg-surface p-3 backdrop-blur"><LifeRadar/></div></div></section>
 <section className="py-24 md:py-36"><div className="mb-14 max-w-3xl"><p className="eyebrow mb-4 text-violet">Personal insights</p><h2 className="display-md">Your data starts telling a story.</h2></div><div className="grid gap-px overflow-hidden rounded-[2rem] border border-line bg-line lg:grid-cols-2">{[
  ['Sleep + movement','You complete 31% more workouts after sleeping at least 7½ hours.',Moon],['Attention','Screen time above 4 hours is associated with lower evening focus.',Smartphone],['Weekly rhythm','Wednesday is your most consistent day.',TrendingUp],['Reading','Reading consistency has improved for four consecutive weeks.',Sparkles],['Mood + exercise','Your average mood is 18% higher on exercise days.',Dumbbell]
 ].map(([label,copy,Icon],i)=>{const Glyph=Icon as typeof Moon;return <div key={label as string} className={`bg-canvas p-7 sm:p-9 ${i===4?'lg:col-span-2':''}`}><Glyph size={18} className="mb-14 text-violet"/><p className="eyebrow mb-3 text-muted">{label as string}</p><p className="max-w-xl text-xl font-semibold leading-snug tracking-[-.025em]">“{copy as string}”</p></div>})}</div></section>
 <section className="rounded-[2rem] bg-[#15131c] px-5 py-20 text-white sm:px-10 md:py-28"><div className="mx-auto max-w-3xl text-center"><p className="eyebrow mb-4 text-lavender">Cause and effect</p><h2 className="display-md">Learn what actually moves you forward.</h2></div><div className="mt-16 grid gap-4 lg:grid-cols-[1fr_auto_1fr_auto_1fr]"><FlowNode icon={Moon} title="Sleep" detail="7.5h+ average"/><FlowArrow/><FlowNode title="Gym Completion" detail="+31%" accent/><FlowArrow/><FlowNode title="Mood" detail="+18%" accent/></div><div className="mx-auto mt-5 grid max-w-4xl gap-4 lg:grid-cols-[1fr_auto_1fr]"><FlowNode icon={Smartphone} title="Screen Time" detail="Above 4 hours"/><FlowArrow negative/><FlowNode title="Sleep Quality" detail="−21%"/><FlowNode icon={BrainCircuit} title="Deep Work" detail="90+ minutes"/><FlowArrow/><FlowNode icon={Target} title="Goal Progress" detail="+26%" accent/></div><p className="mx-auto mt-12 max-w-xl text-center text-xs leading-relaxed text-white/35">Directional relationships based on your selected data. Association can guide reflection; it does not imply certainty.</p></section>
 <section className="py-24 md:py-36"><div className="mb-14 max-w-2xl"><p className="eyebrow mb-4 text-violet">Weekly review</p><h2 className="display-md">See what changed.</h2></div><div className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-[2rem] border border-line bg-surface p-6 sm:p-8"><div className="mb-10 flex items-start justify-between"><div><p className="text-xs text-muted">Overall Score</p><strong className="mt-1 block text-5xl tracking-[-.06em]">82%</strong></div><span className="flex items-center gap-1 text-sm font-bold text-violet"><ArrowUp size={14}/>7%</span></div><div className="grid grid-cols-2 gap-6">{[['Best Habit','Reading — 94%'],['Longest Streak','No Alcohol — 37 days'],['Needs Attention','Sleep — 63%'],['Best Day','Wednesday — 91%']].map(([l,v])=><div key={l}><p className="text-[10px] text-muted">{l}</p><p className="mt-1 text-sm font-bold">{v}</p></div>)}</div><div className="mt-8 grid grid-cols-2 gap-2 border-t border-line pt-6 sm:grid-cols-4">{[['Sleep','+34 min',true],['Screen Time','−17%',false],['Deep Work','+22%',true],['Gym','+1 session',true]].map(([l,v,up])=><div key={l as string}><p className="text-[9px] text-muted">{l as string}</p><p className="mt-1 flex items-center gap-1 text-xs font-bold">{up?<ArrowUp size={10}/>:<ArrowDown size={10}/>} {v as string}</p></div>)}</div></div><div className="space-y-3">{['What went well?','What made this week difficult?','What will you change next week?'].map((prompt,i)=><label key={prompt} className="block rounded-2xl border border-line bg-surface-raised p-5"><span className="text-xs font-bold">{prompt}</span><textarea className="mt-3 min-h-16 w-full resize-none bg-transparent text-sm outline-none placeholder:text-subtle" placeholder={i===0?'I made space for…':'Write a quiet note…'}/></label>)}</div></div></section>
 <section className="border-y border-line py-24 md:py-36"><div className="mb-12 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow mb-4 text-violet">365 days</p><h2 className="display-md">See yourself showing up.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted">Hover any day to see its date, completion, and strongest habit. Small actions become a visible body of work.</p></div><ActivityHeatmap/><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[['90-day consistency','87%'],['Recovery speed','1.4 days'],['Monthly adherence','84%'],['Best week','May 12–18']].map(([l,v])=><div key={l}><p className="text-[10px] uppercase tracking-widest text-muted">{l}</p><p className="mt-2 text-2xl font-semibold tracking-[-.04em]">{v}</p></div>)}</div><div className="mt-14 max-w-3xl"><h3 className="heading-lg">Missing one day shouldn’t erase a month of progress.</h3><p className="mt-4 text-sm leading-relaxed text-muted">Completed, partial, missed, rest day, and planned skip all tell different stories. Form preserves the shape of your consistency without turning an imperfect day into failure.</p><div className="mt-6 flex flex-wrap gap-2">{['Completed','Partial','Missed','Rest Day','Planned Skip'].map(x=><span key={x} className="rounded-lg border border-line bg-surface px-3 py-2 text-[10px] font-semibold">{x}</span>)}</div></div></section>
 <section className="py-24 md:py-36"><div className="grid items-center gap-12 rounded-[2rem] bg-lilac/30 p-7 dark:bg-violet/10 sm:p-12 lg:grid-cols-[1fr_auto]"><div><p className="eyebrow mb-4 text-violet">Templates</p><h2 className="display-md">Don’t want to start from scratch?</h2><p className="body-lg mt-5 max-w-xl text-muted">Start with a system built for your goal, then reshape every detail around your life.</p></div><Link href="/templates"><Button size="lg">Explore templates <ArrowRight size={16}/></Button></Link></div></section>
 </>}
function FlowNode({icon:Icon=Flame,title,detail,accent=false}:{icon?:typeof Flame;title:string;detail:string;accent?:boolean}){return <div className={`rounded-2xl border p-5 ${accent?'border-lavender/30 bg-violet/15':'border-white/10 bg-white/[.04]'}`}><Icon size={16} className="mb-8 text-lavender"/><p className="text-xs text-white/45">{title}</p><strong className="mt-1 block text-xl">{detail}</strong></div>}
function FlowArrow({negative=false}:{negative?:boolean}){return <div className="flex items-center justify-center text-xs font-bold text-lavender"><span className="lg:hidden">↓</span><span className="hidden lg:inline">→ {negative?'−21%':'+'}</span></div>}
