"use client";

import { useState } from "react";
import { BarChart3, BookOpen, CalendarDays, Check, CircleDot, Clock3, Droplets, Flame, GripVertical, LayoutDashboard, Moon, Plus, Settings2, Star, Target, TrendingUp, Type } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const palette=[[CircleDot,"Tracker"],[Type,"Number"],[Clock3,"Timer"],[Star,"Rating"],[Target,"Goal"],[BarChart3,"Chart"],[TrendingUp,"Progress"],[LayoutDashboard,"Heatmap"],[BookOpen,"Journal"],[Flame,"Streak"],[CalendarDays,"Calendar"]] as const;
type DemoWidget={id:number;title:string;type:string;value:string;goal:string;accent:string};
const initial:DemoWidget[]=[{id:1,title:"Sleep",type:"Duration",value:"7h 42m",goal:"of 8 hours",accent:"#7356E8"},{id:2,title:"Water",type:"Number",value:"2.4 L",goal:"of 3 litres",accent:"#6D72D8"},{id:3,title:"Focus trend",type:"Chart",value:"+18%",goal:"Last 7 days",accent:"#9C7CFF"}];

export function InteractiveBuilder(){
 const [widgets,setWidgets]=useState(initial),[selectedId,setSelectedId]=useState(1),[preview,setPreview]=useState(false),[published,setPublished]=useState(false);const selected=widgets.find(widget=>widget.id===selectedId);
 const patch=(change:Partial<DemoWidget>)=>setWidgets(items=>items.map(widget=>widget.id===selectedId?{...widget,...change}:widget));
 const add=(type:string)=>{const id=Math.max(0,...widgets.map(widget=>widget.id))+1;setWidgets(items=>[...items,{id,title:type,type,value:type==="Rating"?"8 / 10":type==="Timer"?"25 min":"Ready",goal:"Daily",accent:"#9C7CFF"}]);setSelectedId(id);setPreview(false)};
 const remove=()=>{if(!selected)return;const remaining=widgets.filter(widget=>widget.id!==selected.id);setWidgets(remaining);setSelectedId(remaining[0]?.id||0)};
 return <div className="builder-ui overflow-hidden rounded-[1.75rem] border border-line bg-surface-raised shadow-[0_35px_90px_rgba(38,30,71,.12)]">
  <div className="flex min-h-14 items-center justify-between gap-3 border-b border-line px-4"><div className="flex items-center gap-2 text-xs font-bold"><span className="grid size-7 place-items-center rounded-lg bg-ink text-canvas"><Settings2 size={12}/></span>Morning dashboard <span className="hidden font-normal text-muted sm:inline">· interactive demo</span></div><div className="flex items-center gap-2"><Button size="sm" variant="ghost" aria-pressed={preview} onClick={()=>setPreview(value=>!value)}>{preview?"Edit":"Preview"}</Button><Button size="sm" onClick={()=>setPublished(true)}>{published?<><Check size={13}/>Published</>:"Publish"}</Button></div></div>
  <div className={cn("grid min-h-[560px]",preview?"grid-cols-1":"lg:grid-cols-[190px_1fr_250px]")}>
   {!preview&&<aside className="border-b border-line p-3 lg:border-b-0 lg:border-r"><p className="eyebrow mb-3 px-2 text-subtle">Add to canvas</p><div className="grid grid-cols-4 gap-1.5 sm:grid-cols-6 lg:grid-cols-2">{palette.map(([Icon,label])=><button key={label} onClick={()=>add(label)} className="focus-ring flex min-h-16 flex-col items-center justify-center gap-2 rounded-xl border border-transparent p-2 text-[10px] font-semibold text-muted hover:border-line hover:bg-canvas hover:text-ink"><Icon aria-hidden="true" size={16}/>{label}</button>)}</div></aside>}
   <div className="relative overflow-hidden bg-[radial-gradient(var(--line)_1px,transparent_1px)] [background-size:20px_20px] p-4 sm:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-muted">Health & focus</p><h3 className="mt-1 text-2xl font-semibold tracking-[-.04em]">My daily rhythm</h3></div><Button size="icon" variant="secondary" aria-label="Add a tracker widget" onClick={()=>add("Tracker")}><Plus size={16}/></Button></div><div className="grid gap-3 sm:grid-cols-2">{widgets.map((widget,index)=><button key={widget.id} onClick={()=>{setSelectedId(widget.id);setPreview(false)}} className={cn("focus-ring relative min-h-44 rounded-2xl border bg-surface-raised p-5 text-left shadow-soft transition",selectedId===widget.id&&!preview?"border-violet ring-1 ring-violet":"border-line hover:border-violet/40",widget.type==="Chart"&&"sm:col-span-2")}><div className="flex justify-between"><span className="grid size-9 place-items-center rounded-xl" style={{background:`${widget.accent}1f`,color:widget.accent}}>{widget.type==="Chart"?<TrendingUp size={17}/>:index%2?<Droplets size={17}/>:<Moon size={17}/>}</span>{!preview&&<GripVertical aria-hidden="true" size={17} className="text-subtle"/>}</div><p className="mt-8 text-xs text-muted">{widget.title}</p><div className="mt-1 flex items-end justify-between gap-3"><strong className="text-2xl tracking-[-.05em]">{widget.value}</strong><span className="text-[10px] text-muted">{widget.goal}</span></div>{widget.type==="Chart"?<div className="mt-5 flex h-12 items-end gap-1">{[35,48,42,61,58,75,82].map((height,i)=><span key={i} className="flex-1 rounded-t-sm" style={{height:`${height}%`,background:widget.accent}}/>)}</div>:<div className="mt-4 h-1.5 rounded-full bg-line"><div className="h-full w-3/4 rounded-full" style={{background:widget.accent}}/></div>}</button>)}</div></div>
   {!preview&&<aside className="border-t border-line p-5 lg:border-l lg:border-t-0"><div className="mb-6"><p className="text-xs font-bold">{selected?.title||"Widget"} settings</p><p className="mt-1 text-[10px] text-muted">Changes update the canvas instantly.</p></div>{selected?<div className="space-y-4"><Field label="Title" value={selected.title} onChange={title=>patch({title})}/><Field label="Value" value={selected.value} onChange={value=>patch({value})}/><Field label="Goal or caption" value={selected.goal} onChange={goal=>patch({goal})}/><label className="block"><span className="mb-2 block text-[10px] font-semibold text-muted">Type</span><select value={selected.type} onChange={event=>patch({type:event.target.value})} className="focus-ring min-h-11 w-full rounded-xl border border-line bg-canvas px-3 text-xs"><option>Tracker</option><option>Number</option><option>Duration</option><option>Rating</option><option>Chart</option></select></label><div><span className="mb-2 block text-[10px] font-semibold text-muted">Accent</span><div className="flex gap-2">{["#7356E8","#6D72D8","#FFC4A8","#F5C5D8"].map(color=><button key={color} aria-label={`Use ${color} accent`} onClick={()=>patch({accent:color})} style={{background:color}} className={cn("size-9 rounded-full",selected.accent===color&&"ring-2 ring-violet ring-offset-2 ring-offset-surface-raised")}/>)}</div></div><button onClick={remove} className="focus-ring min-h-11 w-full rounded-xl border border-line text-xs font-semibold text-muted hover:bg-canvas hover:text-ink">Remove widget</button></div>:<p className="text-xs text-muted">Add a widget to begin.</p>}</aside>}
  </div>
 </div>
}

function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="block"><span className="mb-2 block text-[10px] font-semibold text-muted">{label}</span><input value={value} onChange={event=>onChange(event.target.value)} className="focus-ring min-h-11 w-full rounded-xl border border-line bg-canvas px-3 text-xs"/></label>}
