"use client";

import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, Crown, Heart, LayoutDashboard, Sparkles, Star, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ActivityHeatmap, WeeklyLineChart } from "@/components/charts/analytics-charts";
import { cn } from "@/lib/utils";

type Template={title:string;creator:string;rating:string;users:string;price:string;theme:string;accent:string;description:string};
const templates:Template[]=[
 {title:"Student OS",creator:"Maya Chen",rating:"4.9",users:"12.4k",price:"Free",theme:"Warm Paper",accent:"bg-peach/35",description:"Study blocks, exam countdowns, reading, sleep and a calm weekly review."},
 {title:"75 Hard",creator:"Jordan Lee",rating:"4.8",users:"8.7k",price:"₹399",theme:"Midnight",accent:"bg-[#17151f] text-white",description:"A rigorous challenge tracker with progress photos, workouts and recovery."},
 {title:"Deep Work",creator:"Studio Form",rating:"4.9",users:"18.2k",price:"Free",theme:"Lavender",accent:"bg-lilac/40",description:"Protect focus time and understand the conditions behind your best work."},
 {title:"Fitness Transformation",creator:"Nadia Moves",rating:"4.7",users:"6.1k",price:"₹599",theme:"Aurora",accent:"bg-blue-violet/25",description:"Training volume, strength progress, nutrition habits and recovery in one view."},
 {title:"Dopamine Reset",creator:"Quiet Systems",rating:"4.8",users:"4.9k",price:"₹249",theme:"Minimal",accent:"bg-surface-raised",description:"A gentle structure for attention, screen time and restorative routines."},
 {title:"Exam Preparation",creator:"Akash Rao",rating:"4.9",users:"9.3k",price:"Free",theme:"Cloud",accent:"bg-blue-violet/15",description:"Syllabus progress, mock scores, revision rhythm and exam readiness."},
 {title:"Morning Routine",creator:"Avery Lane",rating:"4.6",users:"21k",price:"Free",theme:"Warm Paper",accent:"bg-blush/30",description:"A beautifully simple start-of-day ritual with flexible check-ins."},
 {title:"Reading Challenge",creator:"Paper & Hours",rating:"4.9",users:"7.8k",price:"₹199",theme:"Dark Academia",accent:"bg-[#2b241f] text-[#f4e8d2]",description:"Books, pages, notes and a year of reading made visible."},
 {title:"Financial Discipline",creator:"Future Self",rating:"4.7",users:"3.2k",price:"₹449",theme:"Forest",accent:"bg-[#243229] text-white",description:"Saving, mindful spending and financial habits without spreadsheet anxiety."},
 {title:"Founder OS",creator:"Northstar",rating:"4.8",users:"5.4k",price:"₹799",theme:"Midnight",accent:"bg-[#15131c] text-white",description:"Focus, energy, company goals and founder health in balance."},
 {title:"Sleep Reset",creator:"Rest Lab",rating:"4.9",users:"11.1k",price:"Free",theme:"Midnight",accent:"bg-[#242039] text-white",description:"Bedtime consistency, duration, quality and the habits that affect sleep."},
 {title:"Personal Growth",creator:"Studio Form",rating:"5.0",users:"26k",price:"Free",theme:"Lavender",accent:"bg-lilac/35",description:"A balanced starting system for habits, goals, mood and reflection."},
];
const themes=[['Cloud','#eef2f7'],['Midnight','#15131c'],['Lavender','#d9ccff'],['Warm Paper','#efe6d5'],['Forest','#243229'],['Dark Academia','#2b241f'],['Minimal','#ffffff'],['Aurora','#6d72d8']];

function Preview({template}:{template:Template}){return <div className={cn("relative h-44 overflow-hidden rounded-t-[1.35rem] p-4",template.accent)}><div className="mb-4 flex justify-between"><span className="text-[9px] font-bold uppercase tracking-widest opacity-55">{template.theme}</span><LayoutDashboard size={14}/></div><div className="grid grid-cols-[1fr_.7fr] gap-2"><div className="rounded-xl bg-white/45 p-3 text-[#0c0c10] backdrop-blur dark:bg-white/10 dark:text-white"><p className="text-[8px] opacity-50">Weekly score</p><strong className="text-2xl">84</strong><div className="mt-4 h-1 rounded bg-black/10"><div className="h-full w-4/5 rounded bg-violet"/></div></div><div className="rounded-xl bg-white/45 p-3 text-[#0c0c10] backdrop-blur dark:bg-white/10 dark:text-white"><p className="text-[8px] opacity-50">Streak</p><strong className="text-xl">12d</strong><div className="mt-5 flex gap-1">{[1,1,1,0,1].map((x,i)=><span key={i} className={cn("size-2 rounded-sm",x?"bg-violet":"bg-black/10")}/>)}</div></div></div></div>}
export function TemplatesScreen(){const [selected,setSelected]=useState<Template|null>(null);const [theme,setTheme]=useState(2);const [used,setUsed]=useState<string[]>([]);return <div className="min-h-screen bg-canvas"><header className="sticky top-0 z-40 border-b border-line bg-canvas/85 backdrop-blur-xl"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-5"><Link href="/" className="flex items-center gap-2 text-sm font-bold"><span className="grid size-8 place-items-center rounded-xl bg-ink text-canvas"><Sparkles size={14}/></span>form</Link><Link href="/builder"><Button size="sm">Open builder</Button></Link></div></header><main><section className="mx-auto max-w-7xl px-5 pb-16 pt-16 sm:px-8 sm:pt-24"><Link href="/" className="mb-8 inline-flex items-center gap-1 text-xs text-muted"><ArrowLeft size={13}/>Home</Link><div className="max-w-3xl"><p className="eyebrow mb-4 text-violet">Template gallery</p><h1 className="display-md">Don’t want to start from scratch?</h1><p className="body-lg mt-5 text-muted">Start with a system built for your goal. Keep what works, change what doesn’t.</p></div><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{templates.map((template,i)=><button key={template.title} onClick={()=>setSelected(template)} className={cn("overflow-hidden rounded-[1.5rem] border border-line bg-surface text-left shadow-soft transition-transform hover:-translate-y-1",i===0&&"sm:col-span-2 lg:col-span-1")}><Preview template={template}/><div className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold tracking-[-.03em]">{template.title}</h2><p className="mt-1 text-[10px] text-muted">by {template.creator}</p></div><span className="rounded-md bg-ink px-2 py-1 text-[9px] font-bold text-canvas">{template.price}</span></div><div className="mt-5 flex items-center gap-4 text-[10px] text-muted"><span className="flex items-center gap-1"><Star size={11} fill="currentColor"/>{template.rating}</span><span className="flex items-center gap-1"><Users size={11}/>{template.users}</span><span className="ml-auto font-semibold text-ink">Preview →</span></div></div></button>)}</div></section>
<section className="border-y border-line py-20"><div className="mx-auto grid max-w-7xl items-center gap-12 px-5 sm:px-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow mb-4 text-violet">Themes</p><h2 className="display-md">Change the atmosphere.</h2><p className="mt-5 text-sm leading-relaxed text-muted">Your data stays yours while the entire visual character changes around it.</p><div className="mt-7 flex flex-wrap gap-2">{themes.map(([name,color],i)=><button key={name} onClick={()=>setTheme(i)} className={cn("rounded-lg border px-3 py-2 text-[10px] font-semibold",theme===i?"border-violet":"border-line")}><span className="mr-2 inline-block size-2 rounded-full align-middle" style={{background:color}}/>{name}</button>)}</div></div><div className="rounded-[2rem] p-6 shadow-soft transition-all duration-700" style={{background:themes[theme][1],color:[1,4,5,7].includes(theme)?'white':'#0c0c10'}}><div className="mb-8 flex justify-between"><div><p className="text-[9px] uppercase tracking-widest opacity-50">Theme preview</p><h3 className="mt-1 text-2xl font-semibold">My quiet progress</h3></div><Heart size={18}/></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/20 p-4 backdrop-blur"><span className="text-[9px] opacity-50">Consistency</span><strong className="block text-3xl">87%</strong><div className="mt-4 h-20"><WeeklyLineChart dark={[1,4,5,7].includes(theme)}/></div></div><div className="rounded-2xl bg-white/20 p-4 backdrop-blur"><span className="text-[9px] opacity-50">90-day rhythm</span><div className="mt-8"><ActivityHeatmap compact dark={[1,4,5,7].includes(theme)}/></div></div></div></div></div></section>
<section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="overflow-hidden rounded-[2rem] bg-ink p-7 text-canvas sm:p-12"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow mb-4 text-lavender">For creators</p><h2 className="display-md">Build a system.<br/>Share it. Sell it.</h2><p className="mt-5 text-sm leading-relaxed text-white/50">Package the workflows that changed your life into something others can make their own.</p></div><div className="rounded-2xl border border-white/10 bg-white/[.05] p-5"><div className="mb-7 flex justify-between"><div><p className="text-[10px] text-white/45">Template Revenue</p><strong className="mt-1 block text-3xl">₹42,650</strong></div><Crown className="text-lavender"/></div><div className="grid grid-cols-3 gap-2">{[['Users','1,842'],['Rating','4.9'],['Completion','74%']].map(([l,v])=><div key={l} className="rounded-xl bg-white/5 p-3"><p className="text-[9px] text-white/40">{l}</p><strong className="mt-1 block text-lg">{v}</strong></div>)}</div><div className="mt-5 flex flex-wrap gap-2">{['Publish','Pricing','Analytics','Branding'].map(x=><Button key={x} variant="ghost" size="sm" className="border border-white/10 text-white/70 hover:bg-white/10 hover:text-white">{x}</Button>)}</div></div></div></div></section></main>{selected&&<div className="fixed inset-0 z-50 grid place-items-end bg-black/40 p-0 backdrop-blur-sm sm:place-items-center sm:p-5"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-[2rem] bg-canvas p-6 sm:rounded-[2rem]"><div className="flex justify-between"><div><p className="eyebrow text-violet">{selected.theme} template</p><h2 className="mt-2 text-3xl font-semibold tracking-[-.05em]">{selected.title}</h2></div><button onClick={()=>setSelected(null)}><X size={19}/></button></div><div className="mt-6 overflow-hidden rounded-2xl"><Preview template={selected}/></div><p className="mt-6 text-sm leading-relaxed text-muted">{selected.description}</p><div className="mt-6 grid gap-4 sm:grid-cols-3"><div><p className="text-[10px] text-muted">Included trackers</p><p className="mt-1 text-sm font-semibold">8 tailored trackers</p></div><div><p className="text-[10px] text-muted">Dashboard widgets</p><p className="mt-1 text-sm font-semibold">12 responsive widgets</p></div><div><p className="text-[10px] text-muted">Creator rating</p><p className="mt-1 text-sm font-semibold">★ {selected.rating} · {selected.users}</p></div></div><div className="mt-8 flex justify-end"><Button onClick={()=>setUsed(x=>[...x,selected.title])}>{used.includes(selected.title)?<><Check size={15}/>Added to library</>:<>Use Template</>}</Button></div></div></div>}</div>}
