import { NextResponse } from "next/server";
import { z } from "zod";
import { requireUser } from "@/lib/auth/users";
import { assertSupabase,getSupabaseAdmin } from "@/lib/supabase/server";

const schema=z.object({displayName:z.string().trim().min(1).max(100),theme:z.enum(["dark","light","system"]),default_planning_view:z.enum(["DAY","WEEK","MONTH"]),week_start_day:z.union([z.literal(0),z.literal(1)]),animations_enabled:z.boolean(),compact_mode:z.boolean(),timezone:z.string().min(1).max(64),email_digest:z.enum(["OFF","DAILY","WEEKLY"]),weekly_review_reminder:z.boolean(),daily_reminder_time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable()});
export const runtime="nodejs";export const dynamic="force-dynamic";
export async function GET(){const user=await requireUser();if(!user)return NextResponse.json({message:"Unauthenticated"},{status:401});try{const supabase=getSupabaseAdmin();assertSupabase(await supabase.from("user_settings").upsert({user_id:user.id},{onConflict:"user_id",ignoreDuplicates:true}).select("user_id"));const row=assertSupabase(await supabase.from("user_settings").select("theme,default_planning_view,week_start_day,animations_enabled,compact_mode,timezone,email_digest,weekly_review_reminder,daily_reminder_time").eq("user_id",user.id).single()) as Record<string,unknown>;return NextResponse.json({...row,displayName:user.displayName||user.email.split("@")[0],email:user.email,role:user.role},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error("Settings load failed",error);return NextResponse.json({message:"We couldn’t load your preferences."},{status:503})}}
export async function PATCH(request:Request){const user=await requireUser();if(!user)return NextResponse.json({message:"Unauthenticated"},{status:401});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Review the highlighted preferences."},{status:400});const value=parsed.data;try{const {error}=await getSupabaseAdmin().rpc("update_user_settings",{p_user_id:user.id,p_display_name:value.displayName,p_theme:value.theme,p_default_planning_view:value.default_planning_view,p_week_start_day:value.week_start_day,p_animations_enabled:value.animations_enabled,p_compact_mode:value.compact_mode,p_timezone:value.timezone,p_email_digest:value.email_digest,p_weekly_review_reminder:value.weekly_review_reminder,p_daily_reminder_time:value.daily_reminder_time});if(error)throw new Error(`SUPABASE_QUERY_FAILED: ${error.message}`);return NextResponse.json({success:true})}catch(error){console.error("Settings save failed",error);return NextResponse.json({message:"We couldn’t save your preferences."},{status:503})}}
