import type { RowDataPacket } from "mysql2";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getDb } from "@/lib/db";
import { requireUser } from "@/lib/auth/users";

const schema=z.object({displayName:z.string().trim().min(1).max(100),theme:z.enum(["dark","light","system"]),default_planning_view:z.enum(["DAY","WEEK","MONTH"]),week_start_day:z.union([z.literal(0),z.literal(1)]),animations_enabled:z.boolean(),compact_mode:z.boolean(),timezone:z.string().min(1).max(64),email_digest:z.enum(["OFF","DAILY","WEEKLY"]),weekly_review_reminder:z.boolean(),daily_reminder_time:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable()});
export const runtime="nodejs";export const dynamic="force-dynamic";
export async function GET(){const user=await requireUser();if(!user)return NextResponse.json({message:"Unauthenticated"},{status:401});try{await getDb().execute("INSERT IGNORE INTO user_settings (user_id) VALUES (?)",[user.id]);const [rows]=await getDb().query<(RowDataPacket&{theme:string;default_planning_view:string;week_start_day:number;animations_enabled:number;compact_mode:number;timezone:string;email_digest:string;weekly_review_reminder:number;daily_reminder_time:string|null})[]>("SELECT theme,default_planning_view,week_start_day,animations_enabled,compact_mode,timezone,email_digest,weekly_review_reminder,TIME_FORMAT(daily_reminder_time,'%H:%i') daily_reminder_time FROM user_settings WHERE user_id=?",[user.id]);const row=rows[0];return NextResponse.json({...row,displayName:user.displayName||user.email.split("@")[0],email:user.email,role:user.role,animations_enabled:Boolean(row.animations_enabled),compact_mode:Boolean(row.compact_mode),weekly_review_reminder:Boolean(row.weekly_review_reminder)},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error("Settings load failed",error);return NextResponse.json({message:"We couldn’t load your preferences."},{status:503})}}
export async function PATCH(request:Request){const user=await requireUser();if(!user)return NextResponse.json({message:"Unauthenticated"},{status:401});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({message:"Review the highlighted preferences."},{status:400});const value=parsed.data;try{const connection=await getDb().getConnection();try{await connection.beginTransaction();await connection.execute("UPDATE users SET display_name=? WHERE id=?",[value.displayName,user.id]);await connection.execute("INSERT INTO user_settings (user_id,theme,default_planning_view,week_start_day,animations_enabled,compact_mode,timezone,email_digest,weekly_review_reminder,daily_reminder_time) VALUES (?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE theme=VALUES(theme),default_planning_view=VALUES(default_planning_view),week_start_day=VALUES(week_start_day),animations_enabled=VALUES(animations_enabled),compact_mode=VALUES(compact_mode),timezone=VALUES(timezone),email_digest=VALUES(email_digest),weekly_review_reminder=VALUES(weekly_review_reminder),daily_reminder_time=VALUES(daily_reminder_time)",[user.id,value.theme,value.default_planning_view,value.week_start_day,value.animations_enabled,value.compact_mode,value.timezone,value.email_digest,value.weekly_review_reminder,value.daily_reminder_time]);await connection.commit()}catch(error){await connection.rollback();throw error}finally{connection.release()}return NextResponse.json({success:true})}catch(error){console.error("Settings save failed",error);return NextResponse.json({message:"We couldn’t save your preferences."},{status:503})}}
