import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ArrowLeft, BarChart3, CalendarDays, CheckCircle2, Eye, Sparkles, Target } from "lucide-react";
import { requireRole } from "@/lib/auth/users";
import { getAdminUser, recordAuditEvent } from "@/lib/admin/users";

export const dynamic="force-dynamic";
export default async function AdminUserWorkspace({params}:{params:Promise<{id:string}>}){const admin=await requireRole("ADMIN");if(!admin)redirect("/today");const id=Number((await params).id);if(!Number.isSafeInteger(id))notFound();const user=await getAdminUser(id);if(!user)notFound();await recordAuditEvent({actorId:admin.id,targetId:user.id,action:"USER_WORKSPACE_VIEWED"});const completion=user.entryCount?Math.round(user.completedCount/user.entryCount*100):0;return <div data-theme="dark" className="min-h-screen bg-[#09090d] text-white"><div className="sticky top-0 z-50 flex min-h-14 items-center justify-between gap-4 border-b border-lavender/20 bg-[#15131c]/90 px-4 backdrop-blur-xl sm:px-7"><div className="flex min-w-0 items-center gap-3"><Eye size={15} className="shrink-0 text-lavender"/><p className="truncate text-xs"><strong>Read-only admin view</strong><span className="ml-2 text-white/40">You are viewing {user.displayName||user.email}&apos;s workspace</span></p></div><Link href="/admin" className="flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-[10px] font-semibold text-white/50 hover:bg-white/5 hover:text-white"><ArrowLeft size={13}/>Back to admin</Link></div><main className="mx-auto max-w-[1480px] px-4 py-8 sm:px-7 lg:px-10"><header className="flex flex-col gap-5 border-b border-white/[.07] pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-lavender/70">User workspace</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em]">{user.displayName||"Unnamed user"}</h1><p className="mt-3 text-sm text-white/40">{user.email} · Joined {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeZone:"Asia/Kolkata"}).format(new Date(user.createdAt))}</p></div><span className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-2 text-xs text-white/55">{user.isActive?"Active account":"Disabled account"}</span></header><section className="grid gap-3 py-7 sm:grid-cols-2 lg:grid-cols-4"><WorkspaceMetric icon={Target} label="Trackers" value={user.trackerCount}/><WorkspaceMetric icon={CalendarDays} label="Entries" value={user.entryCount}/><WorkspaceMetric icon={CheckCircle2} label="Completed" value={user.completedCount}/><WorkspaceMetric icon={BarChart3} label="Completion" value={`${completion}%`}/></section><section className="grid min-h-[390px] place-items-center rounded-[2rem] border border-white/[.08] bg-white/[.035] p-8 text-center"><div className="max-w-md"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-lavender/10 text-lavender"><Sparkles size={21}/></span><h2 className="mt-5 text-xl font-semibold">No persisted workspace activity yet.</h2><p className="mt-3 text-sm leading-6 text-white/40">This view is wired to real user-owned trackers and entries. As the user creates and logs data through the persisted product APIs, their dashboard will appear here without exposing or fabricating demo content.</p></div></section></main></div>}
function WorkspaceMetric({icon:Icon,label,value}:{icon:typeof Target;label:string;value:number|string}){return <div className="rounded-2xl border border-white/[.08] bg-white/[.035] p-5"><Icon size={15} className="text-lavender"/><p className="mt-6 text-[9px] font-bold uppercase tracking-widest text-white/30">{label}</p><strong className="mt-2 block text-3xl tracking-[-.05em]">{value}</strong></div>}
