ALTER TABLE trackers
    ADD COLUMN detail VARCHAR(255) NOT NULL DEFAULT '' AFTER name,
    ADD COLUMN unit VARCHAR(30) NOT NULL DEFAULT '' AFTER target_value,
    ADD COLUMN sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0 AFTER unit;
