CREATE TABLE user_top_focus (
    user_id BIGINT UNSIGNED PRIMARY KEY,
    tracker_id BIGINT UNSIGNED NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_top_focus_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_top_focus_tracker FOREIGN KEY (tracker_id) REFERENCES trackers(id) ON DELETE CASCADE
);
