-- Run once in the Supabase SQL editor. Supabase Auth owns credentials and sessions.
create extension if not exists pgcrypto;

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null unique,
  display_name text,
  role text not null default 'USER' check (role in ('ADMIN','USER')),
  is_active boolean not null default true,
  session_version integer not null default 1,
  last_login_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trackers (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  name varchar(140) not null,
  detail varchar(255) not null default '',
  type text not null check (type in ('BOOLEAN','NUMBER','DURATION','RATING','COUNT','TIME')),
  target_value numeric(14,3),
  unit varchar(30) not null default '',
  sort_order integer not null default 0,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists trackers_user_active_idx on public.trackers(user_id,is_archived);

create table if not exists public.tracker_entries (
  id bigint generated by default as identity primary key,
  tracker_id bigint not null references public.trackers(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  entry_date date not null,
  numeric_value numeric(14,3),
  boolean_value boolean,
  status text not null default 'PENDING' check (status in ('COMPLETE','PARTIAL','MISSED','PLANNED_SKIP','REST_DAY','PENDING')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tracker_id,entry_date)
);
create index if not exists entries_user_date_idx on public.tracker_entries(user_id,entry_date desc);

create table if not exists public.weekly_plan_items (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  tracker_id bigint not null references public.trackers(id) on delete cascade,
  planned_date date not null,
  created_at timestamptz not null default now(),
  unique(tracker_id,planned_date)
);
create index if not exists weekly_plan_user_date_idx on public.weekly_plan_items(user_id,planned_date);

create table if not exists public.user_top_focus (
  user_id bigint primary key references public.users(id) on delete cascade,
  tracker_id bigint not null references public.trackers(id) on delete cascade,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_settings (
  user_id bigint primary key references public.users(id) on delete cascade,
  theme text not null default 'dark' check (theme in ('dark','light','system')),
  default_planning_view text not null default 'DAY' check (default_planning_view in ('DAY','WEEK','MONTH')),
  week_start_day smallint not null default 1 check (week_start_day in (0,1)),
  animations_enabled boolean not null default true,
  compact_mode boolean not null default false,
  timezone varchar(64) not null default 'Asia/Kolkata',
  email_digest text not null default 'WEEKLY' check (email_digest in ('OFF','DAILY','WEEKLY')),
  weekly_review_reminder boolean not null default true,
  daily_reminder_time time,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.users(id) on delete set null,
  target_user_id bigint references public.users(id) on delete set null,
  action varchar(80) not null,
  metadata jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_created_idx on public.admin_audit_logs(created_at desc);

create table if not exists public.auth_rate_limits (
  scope varchar(48) not null,
  key_hash char(64) not null,
  window_started_at timestamptz not null default now(),
  attempts integer not null default 1,
  blocked_until timestamptz,
  updated_at timestamptz not null default now(),
  primary key(scope,key_hash)
);

create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  kind text not null check (kind in ('DAILY_PROGRESS','WEEKLY_PROGRESS','WEEKLY_REVIEW')),
  period_key varchar(64) not null,
  status text not null default 'SENDING' check (status in ('SENDING','SENT','FAILED')),
  attempts integer not null default 1 check (attempts between 1 and 5),
  provider_message_id text,
  last_error varchar(500),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,kind,period_key)
);
create index if not exists notification_deliveries_user_created_idx on public.notification_deliveries(user_id,created_at desc);

create or replace function public.touch_updated_at() returns trigger language plpgsql set search_path=public as $$
begin new.updated_at=now();return new;end $$;
drop trigger if exists users_touch_updated_at on public.users;
create trigger users_touch_updated_at before update on public.users for each row execute function public.touch_updated_at();
drop trigger if exists trackers_touch_updated_at on public.trackers;
create trigger trackers_touch_updated_at before update on public.trackers for each row execute function public.touch_updated_at();
drop trigger if exists entries_touch_updated_at on public.tracker_entries;
create trigger entries_touch_updated_at before update on public.tracker_entries for each row execute function public.touch_updated_at();

create or replace function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path=public as $$
declare profile_id bigint; display_value text;
begin
 display_value=coalesce(nullif(trim(new.raw_user_meta_data->>'display_name'),''),split_part(coalesce(new.email,''),'@',1));
 insert into public.users(auth_user_id,email,display_name) values(new.id,lower(new.email),display_value) returning id into profile_id;
 insert into public.user_settings(user_id) values(profile_id);
 insert into public.trackers(user_id,name,detail,type,target_value,unit,sort_order) values
  (profile_id,'Wake before 7','Before 7:00 AM','BOOLEAN',1,'',1),
  (profile_id,'Morning routine','6 step ritual','BOOLEAN',1,'',2),
  (profile_id,'Gym','Movement · 45 min','BOOLEAN',1,'',3),
  (profile_id,'Water','Daily target · 3 L','NUMBER',3,'L',4),
  (profile_id,'Study','Daily target · 120 min','DURATION',120,'min',5),
  (profile_id,'Reading','Daily target · 30 pages','NUMBER',30,'pages',6),
  (profile_id,'Meditation','Daily target · 15 min','DURATION',15,'min',7),
  (profile_id,'Mood','How today feels','RATING',10,'/10',8);
 insert into public.admin_audit_logs(target_user_id,action) values(profile_id,'USER_SIGNED_UP');
 return new;
end $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();

-- Backfill profiles for Auth users that existed before this schema was installed.
insert into public.users(auth_user_id,email,display_name)
select id,lower(email),coalesce(nullif(trim(raw_user_meta_data->>'display_name'),''),split_part(email,'@',1))
from auth.users where email is not null
on conflict do nothing;
insert into public.user_settings(user_id) select id from public.users on conflict do nothing;

create or replace function public.consume_auth_rate_limit(p_scope text,p_key_hash text,p_limit integer,p_window_seconds integer,p_block_seconds integer)
returns table(attempts integer,retry_after integer) language plpgsql security definer set search_path=public as $$
declare row_state public.auth_rate_limits%rowtype;
begin
 if p_limit<1 or p_window_seconds<1 or p_block_seconds<1 then raise exception 'invalid rate limit';end if;
 insert into public.auth_rate_limits(scope,key_hash) values(p_scope,p_key_hash) on conflict do nothing;
 select * into row_state from public.auth_rate_limits where scope=p_scope and key_hash=p_key_hash for update;
 if row_state.blocked_until>now() then
  return query select row_state.attempts,greatest(0,ceil(extract(epoch from row_state.blocked_until-now()))::integer);return;
 end if;
 if row_state.window_started_at<now()-make_interval(secs=>p_window_seconds) then row_state.attempts=1;row_state.window_started_at=now();row_state.blocked_until=null;
 else row_state.attempts=row_state.attempts+1;if row_state.attempts>p_limit then row_state.blocked_until=now()+make_interval(secs=>p_block_seconds);end if;end if;
 update public.auth_rate_limits set attempts=row_state.attempts,window_started_at=row_state.window_started_at,blocked_until=row_state.blocked_until,updated_at=now() where scope=p_scope and key_hash=p_key_hash;
 return query select row_state.attempts,greatest(0,coalesce(ceil(extract(epoch from row_state.blocked_until-now()))::integer,0));
end $$;

create or replace function public.replace_weekly_plan(p_user_id bigint,p_start date,p_end date,p_items jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
 if p_end<p_start then raise exception 'invalid plan range';end if;
 if exists(select 1 from jsonb_to_recordset(p_items) as x(tracker_id bigint,planned_date date) left join public.trackers t on t.id=x.tracker_id and t.user_id=p_user_id and not t.is_archived where t.id is null or x.planned_date not between p_start and p_end) then raise exception 'invalid tracker or date';end if;
 delete from public.weekly_plan_items where user_id=p_user_id and planned_date between p_start and p_end;
 insert into public.weekly_plan_items(user_id,tracker_id,planned_date) select p_user_id,x.tracker_id,x.planned_date from jsonb_to_recordset(p_items) as x(tracker_id bigint,planned_date date);
end $$;

create or replace function public.update_managed_user(p_actor_id bigint,p_target_id bigint,p_role text,p_is_active boolean)
returns void language plpgsql security definer set search_path=public as $$
declare target public.users%rowtype; active_admins integer;
begin
 if p_actor_id=p_target_id then raise exception 'SELF_MANAGEMENT_NOT_ALLOWED';end if;
 select * into target from public.users where id=p_target_id for update;if not found then raise exception 'USER_NOT_FOUND';end if;
 perform id from public.users where role='ADMIN' and is_active order by id for update;
 select count(*) into active_admins from public.users where role='ADMIN' and is_active;
 if target.role='ADMIN' and target.is_active and (coalesce(p_role,target.role)<>'ADMIN' or coalesce(p_is_active,target.is_active)=false) and active_admins<=1 then raise exception 'LAST_ADMIN';end if;
 update public.users set role=coalesce(p_role,role),is_active=coalesce(p_is_active,is_active),session_version=session_version+1 where id=p_target_id;
 insert into public.admin_audit_logs(actor_user_id,target_user_id,action,metadata) values(p_actor_id,p_target_id,'USER_ACCESS_UPDATED',jsonb_build_object('role',p_role,'isActive',p_is_active));
end $$;

create or replace function public.update_user_settings(p_user_id bigint,p_display_name text,p_theme text,p_default_planning_view text,p_week_start_day smallint,p_animations_enabled boolean,p_compact_mode boolean,p_timezone text,p_email_digest text,p_weekly_review_reminder boolean,p_daily_reminder_time time)
returns void language plpgsql security definer set search_path=public as $$
begin
 update public.users set display_name=p_display_name where id=p_user_id;
 if not found then raise exception 'USER_NOT_FOUND';end if;
 insert into public.user_settings(user_id,theme,default_planning_view,week_start_day,animations_enabled,compact_mode,timezone,email_digest,weekly_review_reminder,daily_reminder_time)
 values(p_user_id,p_theme,p_default_planning_view,p_week_start_day,p_animations_enabled,p_compact_mode,p_timezone,p_email_digest,p_weekly_review_reminder,p_daily_reminder_time)
 on conflict(user_id) do update set theme=excluded.theme,default_planning_view=excluded.default_planning_view,week_start_day=excluded.week_start_day,animations_enabled=excluded.animations_enabled,compact_mode=excluded.compact_mode,timezone=excluded.timezone,email_digest=excluded.email_digest,weekly_review_reminder=excluded.weekly_review_reminder,daily_reminder_time=excluded.daily_reminder_time,updated_at=now();
end $$;

create or replace function public.claim_notification_delivery(p_user_id bigint,p_kind text,p_period_key text)
returns bigint language plpgsql security definer set search_path=public as $$
declare claimed_id bigint;
begin
 insert into public.notification_deliveries(user_id,kind,period_key)
 values(p_user_id,p_kind,p_period_key)
 on conflict(user_id,kind,period_key) do update
 set status='SENDING',attempts=public.notification_deliveries.attempts+1,last_error=null,updated_at=now()
 where public.notification_deliveries.attempts<5 and (
  public.notification_deliveries.status='FAILED' or
  (public.notification_deliveries.status='SENDING' and public.notification_deliveries.updated_at<now()-interval '15 minutes')
 )
 returning id into claimed_id;
 return claimed_id;
end $$;

alter table public.users enable row level security;
alter table public.trackers enable row level security;
alter table public.tracker_entries enable row level security;
alter table public.weekly_plan_items enable row level security;
alter table public.user_top_focus enable row level security;
alter table public.user_settings enable row level security;
alter table public.admin_audit_logs enable row level security;
alter table public.auth_rate_limits enable row level security;
alter table public.notification_deliveries enable row level security;

create or replace function public.current_profile_id() returns bigint language sql stable security definer set search_path=public as $$select id from public.users where auth_user_id=(select auth.uid()) and is_active$$;
drop policy if exists users_self_read on public.users;
create policy users_self_read on public.users for select to authenticated using(id=(select public.current_profile_id()));
drop policy if exists trackers_owner on public.trackers;
create policy trackers_owner on public.trackers for all to authenticated using(user_id=(select public.current_profile_id())) with check(user_id=(select public.current_profile_id()));
drop policy if exists entries_owner on public.tracker_entries;
create policy entries_owner on public.tracker_entries for all to authenticated using(user_id=(select public.current_profile_id())) with check(user_id=(select public.current_profile_id()));
drop policy if exists plans_owner on public.weekly_plan_items;
create policy plans_owner on public.weekly_plan_items for all to authenticated using(user_id=(select public.current_profile_id())) with check(user_id=(select public.current_profile_id()));
drop policy if exists focus_owner on public.user_top_focus;
create policy focus_owner on public.user_top_focus for all to authenticated using(user_id=(select public.current_profile_id())) with check(user_id=(select public.current_profile_id()));
drop policy if exists settings_owner on public.user_settings;
create policy settings_owner on public.user_settings for all to authenticated using(user_id=(select public.current_profile_id())) with check(user_id=(select public.current_profile_id()));

grant select on public.users to authenticated;
grant select,insert,update,delete on public.trackers,public.tracker_entries,public.weekly_plan_items,public.user_top_focus,public.user_settings to authenticated;
grant usage,select on all sequences in schema public to authenticated;
revoke all on function public.consume_auth_rate_limit(text,text,integer,integer,integer) from public,anon,authenticated;
revoke all on function public.replace_weekly_plan(bigint,date,date,jsonb) from public,anon,authenticated;
revoke all on function public.update_managed_user(bigint,bigint,text,boolean) from public,anon,authenticated;
revoke all on function public.update_user_settings(bigint,text,text,text,smallint,boolean,boolean,text,text,boolean,time) from public,anon,authenticated;
revoke all on function public.claim_notification_delivery(bigint,text,text) from public,anon,authenticated;
grant execute on function public.consume_auth_rate_limit(text,text,integer,integer,integer) to service_role;
grant execute on function public.replace_weekly_plan(bigint,date,date,jsonb) to service_role;
grant execute on function public.update_managed_user(bigint,bigint,text,boolean) to service_role;
grant execute on function public.update_user_settings(bigint,text,text,text,smallint,boolean,boolean,text,text,boolean,time) to service_role;
grant execute on function public.claim_notification_delivery(bigint,text,text) to service_role;

-- Bootstrap the first administrator after they sign up:
-- update public.users set role='ADMIN' where email='owner@example.com';
