-- Apply after 001_vlocity.sql. Stores idempotent delivery claims for scheduled email.
create table if not exists public.notification_deliveries (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  kind text not null check (kind in ('DAILY_PROGRESS','WEEKLY_PROGRESS','WEEKLY_REVIEW')),
  period_key varchar(64) not null,
  status text not null default 'SENDING' check (status in ('SENDING','SENT','FAILED')),
  attempts integer not null default 1 check (attempts between 1 and 5),
  provider_message_id text,
  last_error varchar(500),
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,kind,period_key)
);
create index if not exists notification_deliveries_user_created_idx on public.notification_deliveries(user_id,created_at desc);

create or replace function public.claim_notification_delivery(p_user_id bigint,p_kind text,p_period_key text)
returns bigint language plpgsql security definer set search_path=public as $$
declare claimed_id bigint;
begin
 insert into public.notification_deliveries(user_id,kind,period_key)
 values(p_user_id,p_kind,p_period_key)
 on conflict(user_id,kind,period_key) do update
 set status='SENDING',attempts=public.notification_deliveries.attempts+1,last_error=null,updated_at=now()
 where public.notification_deliveries.attempts<5 and (
  public.notification_deliveries.status='FAILED' or
  (public.notification_deliveries.status='SENDING' and public.notification_deliveries.updated_at<now()-interval '15 minutes')
 )
 returning id into claimed_id;
 return claimed_id;
end $$;

alter table public.notification_deliveries enable row level security;
revoke all on function public.claim_notification_delivery(bigint,text,text) from public,anon,authenticated;
grant execute on function public.claim_notification_delivery(bigint,text,text) to service_role;
