"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ArrowLeft, ArrowRight, BarChart3, BookOpen, BrainCircuit, BriefcaseBusiness, Check, CircleDollarSign, Dumbbell, Heart, Moon, ShieldCheck, Smartphone, Sparkles, Target, Users, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ActivityHeatmap, ScoreRing, WeeklyLineChart } from "@/components/charts/analytics-charts";
import { cn } from "@/lib/utils";

const categories=[['Health',Heart],['Fitness',Dumbbell],['Learning',BookOpen],['Career',BriefcaseBusiness],['Discipline',ShieldCheck],['Sleep',Moon],['Digital Wellbeing',Smartphone],['Finance',CircleDollarSign],['Relationships',Users],['Mindfulness',BrainCircuit]] as const;
const trackerMap:Record<string,string[]>={Health:['Sleep','Water','Steps','Exercise','Mood'],Fitness:['Workouts','Steps','Training Volume','Recovery'],Learning:['Study Time','Reading','Deep Work','Course Progress'],Career:['Deep Work','Key Outcomes','Learning Hours','Energy'],Discipline:['Morning Routine','Daily Plan','Wake Time','Focus'],Sleep:['Sleep Duration','Bedtime','Sleep Quality','Caffeine'],['Digital Wellbeing']:['Screen Time','Social Media','Phone Pickups','Evening Focus'],Finance:['Savings','No-spend Days','Investing','Budget Review'],Relationships:['Quality Time','Check-ins','Shared Activities','Gratitude'],Mindfulness:['Meditation','Mood','Journal','Breathwork']};
const modes=[{name:'Start Simple',copy:'Four essential trackers and one calm daily view.',icon:Sparkles},{name:'Balanced System',copy:'A thoughtful mix of daily capture and weekly perspective.',icon:Target},{name:'Detailed Dashboard',copy:'Richer metrics, areas, goals, and deeper analytics.',icon:BarChart3}];

export type OnboardingState={categories:string[];trackers:string[];mode:string};

export function OnboardingFlow(){
 const router=useRouter();const root=useRef<HTMLDivElement>(null);const [step,setStep]=useState(1);const [choices,setChoices]=useState<OnboardingState>({categories:[],trackers:[],mode:'Balanced System'});const [built,setBuilt]=useState(false);
 const recommended=useMemo(()=>Array.from(new Set(choices.categories.flatMap(category=>trackerMap[category]??[]))).slice(0,10),[choices.categories]);
 useEffect(()=>{const saved=localStorage.getItem('form-onboarding');if(saved)try{setChoices(JSON.parse(saved))}catch{}},[]);
 useEffect(()=>{localStorage.setItem('form-onboarding',JSON.stringify(choices))},[choices]);
 useEffect(()=>{if(step!==4)return;const timer=window.setTimeout(()=>setBuilt(true),2600);return()=>window.clearTimeout(timer)},[step]);
 useGSAP(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;gsap.fromTo('.onboarding-content',{y:24,opacity:0},{y:0,opacity:1,duration:.7,ease:'power3.out'});if(step===4){gsap.from('.assembling-piece',{y:35,opacity:0,scale:.92,duration:.7,stagger:.16,ease:'power3.out'});gsap.to('.build-orbit',{rotate:360,duration:8,repeat:-1,ease:'none'})}}, {scope:root,dependencies:[step,built],revertOnUpdate:true});
 const toggleCategory=(name:string)=>setChoices(c=>({...c,categories:c.categories.includes(name)?c.categories.filter(x=>x!==name):[...c.categories,name]}));
 const toggleTracker=(name:string)=>setChoices(c=>({...c,trackers:c.trackers.includes(name)?c.trackers.filter(x=>x!==name):[...c.trackers,name]}));
 const next=()=>{if(step===1){setChoices(c=>({...c,trackers:Array.from(new Set([...c.trackers,...recommended.slice(0,6)]))}))}setStep(s=>Math.min(4,s+1))};
 return <div ref={root} className="relative min-h-screen overflow-hidden bg-canvas"><div className="pointer-events-none absolute -left-52 -top-52 size-[34rem] rounded-full bg-lilac/35 blur-[110px] dark:bg-violet/10"/><div className="pointer-events-none absolute -bottom-52 -right-52 size-[32rem] rounded-full bg-peach/30 blur-[120px] dark:bg-blush/5"/><header className="relative z-10 flex h-20 items-center justify-between px-5 sm:px-8"><button onClick={()=>step>1?setStep(step-1):router.push('/')} className="focus-ring flex items-center gap-2 rounded-lg text-sm font-bold"><span className="grid size-8 place-items-center rounded-xl bg-ink text-canvas"><Sparkles size={14}/></span>form</button><div className="hidden items-center gap-2 sm:flex">{[1,2,3,4].map(n=><span key={n} className={cn('h-1.5 rounded-full transition-all duration-500',n<=step?'w-9 bg-violet':'w-5 bg-line')}/>)}</div><button onClick={()=>router.push('/')} className="focus-ring grid size-10 place-items-center rounded-xl text-muted" aria-label="Exit onboarding"><X size={18}/></button></header><main className="relative z-10 mx-auto flex min-h-[calc(100vh-5rem)] max-w-6xl items-center px-5 pb-12 sm:px-8"><div className="onboarding-content w-full">{step===1&&<StepShell eyebrow="A more personal starting point" title="What are you trying to improve?" copy="Choose everything that feels relevant right now. Your system can change as you do."><div className="mx-auto grid max-w-4xl grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{categories.map(([name,Icon])=>{const active=choices.categories.includes(name);return <button key={name} aria-pressed={active} onClick={()=>toggleCategory(name)} className={cn('focus-ring relative flex min-h-32 flex-col justify-between rounded-2xl border p-4 text-left transition-all duration-300 sm:min-h-40 sm:p-5',active?'border-violet bg-lilac/30 shadow-soft dark:bg-violet/15':'border-line bg-surface hover:-translate-y-1 hover:bg-surface-raised')}><Icon size={19} className={active?'text-violet':'text-muted'}/><span className="text-sm font-bold">{name}</span>{active&&<span className="absolute right-3 top-3 grid size-5 place-items-center rounded-full bg-violet text-white"><Check size={11}/></span>}</button>})}</div></StepShell>}
 {step===2&&<StepShell eyebrow="Recommended for you" title="What would you like to measure?" copy="We’ve suggested a focused set from your priorities. Keep only what feels useful."><div className="mx-auto flex max-w-4xl flex-wrap justify-center gap-3">{recommended.map(name=>{const active=choices.trackers.includes(name);return <button key={name} onClick={()=>toggleTracker(name)} aria-pressed={active} className={cn('focus-ring flex min-h-14 items-center gap-3 rounded-2xl border px-5 text-sm font-semibold transition-all',active?'border-violet bg-lilac/35 dark:bg-violet/15':'border-line bg-surface hover:bg-surface-raised')}><span className={cn('grid size-6 place-items-center rounded-lg',active?'bg-violet text-white':'bg-ink/5')}><Check size={12}/></span>{name}</button>})}{recommended.length===0&&<p className="rounded-2xl border border-line bg-surface p-6 text-sm text-muted">Go back and choose at least one area to see personalized recommendations.</p>}</div></StepShell>}
 {step===3&&<StepShell eyebrow="Choose your pace" title="How do you want to start?" copy="You can simplify or add detail at any time. Nothing is locked in."><div className="mx-auto grid max-w-4xl gap-4 md:grid-cols-3">{modes.map(({name,copy,icon:Icon})=>{const active=choices.mode===name;return <button key={name} onClick={()=>setChoices(c=>({...c,mode:name}))} className={cn('focus-ring flex min-h-60 flex-col rounded-[1.5rem] border p-6 text-left transition-all',active?'border-violet bg-surface-raised shadow-soft ring-2 ring-violet/10':'border-line bg-surface hover:-translate-y-1')}><span className={cn('grid size-11 place-items-center rounded-xl',active?'bg-violet text-white':'bg-ink/5')}><Icon size={18}/></span><h2 className="mt-auto text-xl font-semibold tracking-[-.03em]">{name}</h2><p className="mt-2 text-xs leading-relaxed text-muted">{copy}</p>{name==='Balanced System'&&<span className="mt-4 text-[9px] font-bold uppercase tracking-widest text-violet">Recommended</span>}</button>})}</div><div className="mx-auto mt-6 flex max-w-4xl items-center justify-center gap-2 text-xs text-muted"><span>Good match:</span>{choices.categories.slice(0,3).map(x=><span key={x} className="rounded-md bg-ink/5 px-2 py-1">{x}</span>)}</div></StepShell>}
 {step===4&&<div className="text-center"><p className="eyebrow mb-4 text-violet">{built?'Ready when you are':'A system, shaped around you'}</p><h1 className="display-md">{built?'Your dashboard is ready.':'Building your dashboard…'}</h1><p className="mx-auto mt-5 max-w-xl text-sm leading-relaxed text-muted">{built?`${choices.trackers.length} trackers, composed into your ${choices.mode.toLowerCase()}.`:'Connecting your priorities, trackers, and preferred level of detail.'}</p><div className="relative mx-auto mt-12 min-h-[390px] max-w-3xl"><div className="build-orbit absolute left-1/2 top-1/2 size-72 -translate-x-1/2 -translate-y-1/2 rounded-full border border-dashed border-violet/30"/><div className="assembling-piece absolute left-1/2 top-2 z-10 w-[72%] -translate-x-1/2 rounded-[1.5rem] border border-line bg-surface-raised p-5 text-left shadow-soft"><div className="flex justify-between"><div><p className="text-[9px] uppercase tracking-widest text-muted">Your week</p><h3 className="mt-1 text-xl font-semibold">{choices.categories.slice(0,2).join(' + ')||'Personal growth'}</h3></div><ScoreRing score={82} label="" size={72}/></div><div className="mt-3 h-24"><WeeklyLineChart/></div></div><div className="assembling-piece absolute bottom-8 left-1 z-20 w-48 rounded-2xl border border-line bg-surface/90 p-4 text-left shadow-soft backdrop-blur"><p className="text-[9px] text-muted">Daily rhythm</p><div className="mt-4"><ActivityHeatmap compact/></div></div><div className="assembling-piece absolute bottom-3 right-1 z-20 w-44 rounded-2xl border border-line bg-surface/90 p-4 text-left shadow-soft backdrop-blur"><p className="text-[9px] text-muted">Trackers ready</p><p className="mt-1 text-3xl font-semibold">{choices.trackers.length}</p><p className="mt-2 truncate text-[10px] text-muted">{choices.trackers.slice(0,3).join(' · ')}</p></div></div>{built&&<div className="mt-6 flex flex-col justify-center gap-3 sm:flex-row"><Button size="lg" onClick={()=>router.push('/today')}>Enter my dashboard <ArrowRight size={16}/></Button><Button size="lg" variant="secondary" onClick={()=>router.push('/builder')}>Customize first</Button></div>}</div>}
 {step<4&&<div className="mx-auto mt-10 flex max-w-4xl items-center justify-between"><Button variant="ghost" onClick={()=>step===1?router.push('/'):setStep(step-1)}><ArrowLeft size={15}/>Back</Button><Button size="lg" onClick={next} disabled={(step===1&&!choices.categories.length)||(step===2&&!choices.trackers.length)}>Continue <ArrowRight size={15}/></Button></div>}
 </div></main></div>;
}
function StepShell({eyebrow,title,copy,children}:{eyebrow:string;title:string;copy:string;children:React.ReactNode}){return <div><div className="mx-auto mb-10 max-w-3xl text-center sm:mb-14"><p className="eyebrow mb-4 text-violet">{eyebrow}</p><h1 className="display-md">{title}</h1><p className="body-lg mx-auto mt-5 max-w-2xl text-muted">{copy}</p></div>{children}</div>}
