"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { ArrowLeft, CheckCircle2, LoaderCircle } from "lucide-react";
import { AuthCard, AuthShell } from "@/components/auth/auth-shell";
import { AuthField, PasswordField } from "@/components/auth/auth-fields";
import { AuthError } from "@/components/auth/auth-error";

export function ForgotPasswordForm(){const [state,setState]=useState<"idle"|"loading"|"sent">("idle");const [error,setError]=useState("");const [devLink,setDevLink]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setState("loading");setError("");const email=new FormData(event.currentTarget).get("email");try{const response=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const data=await response.json();if(!response.ok){setError(data.message);setState("idle");return}setDevLink(data.developmentLink||"");setState("sent")}catch{setError("We couldn't process that request right now.");setState("idle")}}return <AuthShell><AuthCard>{state==="sent"?<Success title="Check your email" copy="If an account exists, we sent a secure link that expires in 30 minutes." devLink={devLink}/>:<><p className="text-xs font-bold uppercase tracking-[.16em] text-lavender">Account recovery</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em]">Reset your password.</h1><p className="mt-4 text-sm leading-6 text-white/60">Enter the email connected to your account.</p><form onSubmit={submit} className="mt-8 space-y-5"><AuthField name="email" label="Email" type="email" autoComplete="email" placeholder="you@company.com"/>{error&&<AuthError message={error}/>}<button disabled={state==="loading"} className="focus-ring flex min-h-[52px] w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-bold text-black disabled:opacity-60"><LoaderCircle size={16} className={state==="loading"?"animate-spin":"hidden"}/>Send reset link</button></form><BackToSignIn/></>}</AuthCard></AuthShell>}

export function ResetPasswordForm(){const [state,setState]=useState<"idle"|"loading"|"done">("idle");const [error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),password=String(form.get("password")||""),confirm=String(form.get("confirmPassword")||"");if(password.length<8){setError("Password must be at least 8 characters.");return}if(password!==confirm){setError("Passwords do not match.");return}setState("loading");setError("");try{const response=await fetch("/api/auth/reset-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const data=await response.json();if(!response.ok){setError(data.message);setState("idle");return}setState("done")}catch{setError("We couldn't reset your password right now.");setState("idle")}}return <AuthShell><AuthCard>{state==="done"?<Success title="Password updated" copy="Your previous sessions have been invalidated. Sign in with your new password."/>:<><p className="text-xs font-bold uppercase tracking-[.16em] text-lavender">Secure reset</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.055em]">Choose a new password.</h1><form onSubmit={submit} className="mt-8 space-y-5"><PasswordField name="password" label="New password" autoComplete="new-password"/><PasswordField name="confirmPassword" label="Confirm password" autoComplete="new-password"/>{error&&<AuthError message={error}/>}<button disabled={state==="loading"} className="focus-ring flex min-h-[52px] w-full items-center justify-center gap-2 rounded-xl bg-white text-sm font-bold text-black disabled:opacity-60"><LoaderCircle size={16} className={state==="loading"?"animate-spin":"hidden"}/>Update password</button></form><BackToSignIn/></>}</AuthCard></AuthShell>}
function Success({title,copy,devLink}:{title:string;copy:string;devLink?:string}){return <div className="text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-positive/10 text-positive"><CheckCircle2/></span><h1 className="mt-5 text-3xl font-semibold tracking-[-.05em]">{title}</h1><p className="mt-3 text-sm leading-6 text-white/55">{copy}</p>{devLink&&<Link href={devLink} className="mt-5 inline-flex rounded-xl border border-lavender/20 bg-lavender/10 px-4 py-3 text-xs font-bold text-lavender">Open local reset link</Link>}<BackToSignIn/></div>}
function BackToSignIn(){return <Link href="/signin" className="mt-6 flex items-center justify-center gap-2 text-xs font-semibold text-white/45 hover:text-white"><ArrowLeft size={13}/>Back to sign in</Link>}
