"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { DndContext, DragEndEvent, PointerSensor, useSensor, useSensors } from "@dnd-kit/core";
import { SortableContext, arrayMove, rectSortingStrategy, useSortable } from "@dnd-kit/sortable";
import { CSS } from "@dnd-kit/utilities";
import { BarChart3, BookOpen, CalendarDays, Check, CircleDot, Copy, Flame, GripVertical, LayoutDashboard, LineChart, MessageSquareQuote, Plus, Sparkles, Target, Trash2, TrendingUp, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ActivityHeatmap, ScoreRing, WeeklyLineChart } from "@/components/charts/analytics-charts";
import { cn } from "@/lib/utils";
import { VlocityBrand } from "@/components/brand/vlocity-logo";

type WidgetType="Metric"|"Habit List"|"Progress Ring"|"Line Chart"|"Bar Chart"|"Heatmap"|"Streak"|"Calendar"|"Goal"|"Journal"|"Quote"|"Area Score";
type Widget={id:string;type:WidgetType;title:string;source:string;range:string;accent:string;goal:string};
const library:[WidgetType,typeof CircleDot][]=[["Metric",CircleDot],["Habit List",Check],["Progress Ring",TrendingUp],["Line Chart",LineChart],["Bar Chart",BarChart3],["Heatmap",LayoutDashboard],["Streak",Flame],["Calendar",CalendarDays],["Goal",Target],["Journal",BookOpen],["Quote",MessageSquareQuote],["Area Score",Sparkles]];
const seed:Widget[]=[{id:"life",type:"Progress Ring",title:"Life Score",source:"All areas",range:"This week",accent:"#7356E8",goal:"85"},{id:"trend",type:"Line Chart",title:"Consistency",source:"All habits",range:"30 days",accent:"#9C7CFF",goal:"90"},{id:"heat",type:"Heatmap",title:"Daily Rhythm",source:"Completed habits",range:"90 days",accent:"#7356E8",goal:"80"}];
const makeWidget=(type:WidgetType):Widget=>({id:`${type}-${Date.now()}`,type,title:type,source:"All habits",range:"This week",accent:"#7356E8",goal:"80"});

function SortableWidget({widget,selected,onSelect,onRemove,onDuplicate}:{widget:Widget;selected:boolean;onSelect:()=>void;onRemove:()=>void;onDuplicate:()=>void}){const {attributes,listeners,setNodeRef,transform,transition,isDragging}=useSortable({id:widget.id});return <div ref={setNodeRef} style={{transform:CSS.Transform.toString(transform),transition}} onClick={onSelect} className={cn("group relative min-h-48 rounded-2xl border bg-surface-raised p-5 shadow-soft",selected?"border-violet ring-2 ring-violet/15":"border-line",isDragging&&"z-50 opacity-70 shadow-2xl")}><div className="absolute right-3 top-3 flex opacity-0 transition-opacity group-hover:opacity-100"><button onClick={e=>{e.stopPropagation();onDuplicate()}} className="grid size-7 place-items-center rounded-lg hover:bg-ink/5"><Copy size={12}/></button><button onClick={e=>{e.stopPropagation();onRemove()}} className="grid size-7 place-items-center rounded-lg hover:bg-ink/5"><Trash2 size={12}/></button><button {...attributes} {...listeners} className="grid size-7 cursor-grab place-items-center rounded-lg hover:bg-ink/5"><GripVertical size={13}/></button></div><p className="text-[10px] font-bold uppercase tracking-widest text-muted">{widget.type}</p><h3 className="mt-1 text-lg font-semibold">{widget.title}</h3><WidgetVisual widget={widget}/></div>}
function WidgetVisual({widget}:{widget:Widget}){if(widget.type==="Progress Ring"||widget.type==="Area Score")return <div className="mt-3 flex justify-center"><ScoreRing score={82} label="" size={120}/></div>;if(widget.type==="Line Chart"||widget.type==="Bar Chart")return <div className="mt-4 h-28"><WeeklyLineChart/></div>;if(widget.type==="Heatmap")return <div className="mt-8"><ActivityHeatmap compact/></div>;if(widget.type==="Habit List")return <div className="mt-5 space-y-2">{['Reading','Move','Meditate'].map((x,i)=><div key={x} className="flex items-center gap-2 text-xs"><span className={cn("grid size-5 place-items-center rounded-md",i<2?"bg-ink text-canvas":"border border-line")}><Check size={10}/></span>{x}</div>)}</div>;return <div className="mt-10"><strong className="text-4xl tracking-[-.06em]">{widget.type==="Streak"?"14 days":widget.type==="Goal"?"76%":"87%"}</strong><p className="mt-2 text-xs text-muted">Updated just now</p></div>}

export function BuilderScreen(){
 const [widgets,setWidgets]=useState<Widget[]>(seed);const [selected,setSelected]=useState("life");const [trackerOpen,setTrackerOpen]=useState(false);const [step,setStep]=useState(1);const [trackerName,setTrackerName]=useState("");const sensors=useSensors(useSensor(PointerSensor,{activationConstraint:{distance:6}}));
 useEffect(()=>{const saved=localStorage.getItem("form-builder-layout");if(saved)try{setWidgets(JSON.parse(saved))}catch{}},[]);useEffect(()=>{localStorage.setItem("form-builder-layout",JSON.stringify(widgets))},[widgets]);
 const active=widgets.find(w=>w.id===selected);const patch=(changes:Partial<Widget>)=>setWidgets(items=>items.map(w=>w.id===selected?{...w,...changes}:w));const add=(type:WidgetType)=>{const widget=makeWidget(type);setWidgets(x=>[...x,widget]);setSelected(widget.id)};const dragEnd=({active,over}:DragEndEvent)=>{if(over&&active.id!==over.id)setWidgets(items=>arrayMove(items,items.findIndex(x=>x.id===active.id),items.findIndex(x=>x.id===over.id)))};
 return <div className="h-screen overflow-hidden bg-canvas"><header className="flex h-16 items-center justify-between border-b border-line px-4"><Link href="/" aria-label="Vlocity home" className="focus-ring rounded-lg text-sm"><VlocityBrand markClassName="size-7"/><span className="ml-2 font-normal text-muted">/ Builder</span></Link><div className="flex gap-2"><Button variant="secondary" size="sm">Preview</Button><Button size="sm">Publish</Button></div></header><div className="grid h-[calc(100vh-4rem)] lg:grid-cols-[210px_1fr_250px]">
  <aside className="hidden overflow-y-auto border-r border-line p-3 lg:block"><div className="mb-3 flex items-center justify-between px-2"><p className="eyebrow text-muted">Widgets</p><button onClick={()=>setTrackerOpen(true)} className="grid size-7 place-items-center rounded-lg bg-ink text-canvas"><Plus size={13}/></button></div><div className="grid grid-cols-2 gap-1.5">{library.map(([type,Icon])=><button key={type} onClick={()=>add(type)} className="flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl border border-transparent text-[9px] font-semibold text-muted hover:border-line hover:bg-surface-raised hover:text-ink"><Icon size={16}/>{type}</button>)}</div></aside>
  <main className="overflow-y-auto bg-[radial-gradient(var(--line)_1px,transparent_1px)] [background-size:22px_22px] p-4 sm:p-8"><div className="mx-auto max-w-4xl"><div className="mb-8 flex items-end justify-between"><div><p className="eyebrow text-violet">Personal dashboard</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.05em]">My growth system</h1></div><Button className="lg:hidden" size="sm" onClick={()=>add("Metric")}><Plus size={13}/>Widget</Button></div><DndContext sensors={sensors} onDragEnd={dragEnd}><SortableContext items={widgets.map(w=>w.id)} strategy={rectSortingStrategy}><div className="grid gap-4 sm:grid-cols-2">{widgets.map(widget=><SortableWidget key={widget.id} widget={widget} selected={selected===widget.id} onSelect={()=>setSelected(widget.id)} onRemove={()=>setWidgets(x=>x.filter(w=>w.id!==widget.id))} onDuplicate={()=>setWidgets(x=>[...x,{...widget,id:`${widget.id}-copy-${Date.now()}`}])}/>)}</div></SortableContext></DndContext></div></main>
  <aside className="hidden overflow-y-auto border-l border-line bg-surface p-5 lg:block"><p className="eyebrow mb-6 text-muted">Properties</p>{active?<div className="space-y-5"><Property label="Title" value={active.title} onChange={title=>patch({title})}/>{[['Data Source','source'],['Time Range','range'],['Visualization','type'],['Goal','goal'],['Theme','theme']].map(([label,key])=><label key={label} className="block"><span className="mb-2 block text-[10px] font-semibold text-muted">{label}</span><select value={key==='type'?active.type:key==='theme'?'System':active[key as keyof Widget]} onChange={e=>key==='source'?patch({source:e.target.value}):key==='range'?patch({range:e.target.value}):key==='goal'?patch({goal:e.target.value}):undefined} className="h-10 w-full rounded-xl border border-line bg-canvas px-3 text-xs"><option>{key==='type'?active.type:key==='theme'?'System':active[key as keyof Widget]}</option><option>All habits</option><option>30 days</option><option>90 days</option></select></label>)}<div><span className="mb-2 block text-[10px] font-semibold text-muted">Accent</span><div className="flex gap-2">{['#7356E8','#9C7CFF','#FFC4A8','#F5C5D8','#6D72D8'].map(c=><button key={c} onClick={()=>patch({accent:c})} style={{background:c}} className={cn("size-7 rounded-full",active.accent===c&&"ring-2 ring-violet ring-offset-2 ring-offset-canvas")}/>)}</div></div><label className="flex items-center justify-between text-xs font-semibold">Show comparison<input type="checkbox" defaultChecked className="accent-violet"/></label></div>:<p className="text-xs text-muted">Select a widget to edit it.</p>}</aside>
 </div>{trackerOpen&&<TrackerFlow step={step} setStep={setStep} name={trackerName} setName={setTrackerName} close={()=>{setTrackerOpen(false);setStep(1)}} done={()=>{add("Habit List");setTrackerOpen(false);setStep(1)}}/>}</div>
}
function Property({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="block"><span className="mb-2 block text-[10px] font-semibold text-muted">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-xl border border-line bg-canvas px-3 text-xs outline-none focus:border-violet"/></label>}
function TrackerFlow({step,setStep,name,setName,close,done}:{step:number;setStep:(s:number)=>void;name:string;setName:(s:string)=>void;close:()=>void;done:()=>void}){const titles=['What do you want to track?','Choose a type','Set a goal','Choose a schedule','Choose an area','Make it yours'];const options=[[],['Boolean','Number','Duration','Rating','Time','Counter'],['No target','Daily target','Weekly target'],['Every Day','Weekdays','Custom'],['Health','Learning','Career','Fitness','Other'],['Violet','Peach','Blush','Blue']];return <div className="fixed inset-0 z-50 grid place-items-end bg-black/30 backdrop-blur-sm sm:place-items-center"><div className="w-full max-w-lg rounded-t-[2rem] bg-surface-raised p-6 shadow-2xl sm:rounded-[2rem]"><div className="mb-8 flex items-center justify-between"><div><p className="eyebrow text-violet">New tracker · {step}/6</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">{titles[step-1]}</h2></div><button onClick={close}><X size={19}/></button></div>{step===1?<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Morning walk" className="h-14 w-full rounded-xl border border-line bg-canvas px-4 text-sm outline-none focus:border-violet"/>:<div className="grid grid-cols-2 gap-2">{options[step-1].map(option=><button key={option} onClick={()=>step<6?setStep(step+1):done()} className="min-h-14 rounded-xl border border-line bg-canvas px-4 text-left text-sm font-semibold hover:border-violet">{option}</button>)}</div>}<div className="mt-8 flex justify-between"><Button variant="ghost" disabled={step===1} onClick={()=>setStep(step-1)}>Back</Button><Button disabled={step===1&&!name} onClick={()=>step<6?setStep(step+1):done()}>{step===6?'Create tracker':'Continue'}</Button></div></div></div>}
